cmd/up/cloud/controlplane/attach.go
cmd/up/uxp/uxp.go
docs/commands.md
internal/kube/client.go

Updates `--kubeconfig` flags to not explicitly use environment variables and instead fall back on default kubeconfig loader chain used by `kubectl`. This means that `up` is only overriding behavior if an explicit existing path is passed to `--kubeconfig`.
Fixes #77 
Tested this out by creating two different kind clusters and running the following scenarios after exporting kubeconfigs to `first.yaml` and `second.yaml`:
- Add list of paths to `KUBECONFIG` that includes `first.yaml` but not `second.yaml` -- first cluster is used
- Add list of paths to `KUBECONFIG` that includes `second.yaml` but not `first.yaml` -- second cluster is used
- Add list of paths to `KUBECONFIG` that includes `first.yaml` _before_ `second.yaml` -- first cluster is used
- Unset `KUBECONFIG` and current context in …

Match kubectl behavior in commands that use kubeconfig

---

internal/uxp/installers/helm/helm.go

Strips the leading v off of any UXP versions supplied when pulling the
chart so that it matches how Helm caches it. An alternative approach
would be to parse into structured semantic version prior to passing to
Helm, but we prefer to defer that logic to Helm rather than parsing into
semver twice. If additional modification were made by Helm in the
future, this functionality could break, but we would prefer to hit the
issue rather than potentially pulling and installing incorrect UXP versions.
Fixes #84

Strip leading v off of UXP version when pulling chart

---

cmd/up/cloud/controlplane/attach.go
docs/commands.md

Removes setting the kube cluster ID for a control plane when attaching
self-hosted and instead defers the responsibility to the agent upon
connecting.
Fixes #89 
Tested with normal `up cloud xp attach <name> | up uxp connect -` flow and successfully provisioned and connected a self-hosted control plane.

Remove kube cluster ID from attach and defer to agent

---

cmd/up/cloud/cloud.go
docs/commands.md
docs/workflows.md

The xp shorthand for control plane is confusing because xp is associated
with Crossplane. This updates to instead use ctp which maps closer to
the actual term and does not create conceptual conflicts.
**NOTE: this is a breaking syntax change, but all functionality is still achievable.**

Change controlplane alias from xp to ctp

---

cmd/up/cloud/controlplane.go
cmd/up/cloud/controlplane/attach.go
cmd/up/cloud/controlplane/token/create.go
cmd/up/cloud/controlplane/token/delete.go
cmd/up/cloud/controlplane/token/list.go
cmd/up/cloud/controlplane/token/token.go
cmd/up/main.go
docs/commands.md
go.mod

Adds support for managing control plane tokens in the form of the following commands:
```
cloud
cloud controlplane token create <control-plane-ID>
Create a control plane token.
cloud controlplane token delete <token-ID>
Delete a control plane token.
cloud controlplane token list <control-plane-ID>
List tokens for the control plane.
```
Fixes #88 
Fixes #49 (I am suggesting closing #49 with this as I believe it is a better experience to use `up cloud ctp token create` while we don't have uniqueness in control plane names on Upbound Cloud)
I have:
Tested against self-hosted control planes on Upbound Cloud:
1. Attach cluster
```
🤖 (up) up cloud ctp attach test | up uxp connect -
```
2. List control planes
```
🤖 (up) up cloud ctp list
NAME   ID                                     SELF-HOSTED …
```

Add support for managing control plane tokens

---

internal/uxp/installers/helm/helm.go

Currently, when a version is not specified on uxp install or upgrade, we
pull the latest stable chart and cache it without version information in
the dedicated uxp chart cache. This means that if a version that was
installed as the latest was subsequently installed explicitly (i.e. by
providing the version), we would unnecessarily pull the chart again when
it was already in the cache.
This updates the pull logic to save charts pulled as latest with their
appropriate version so that they can be identified in future installs.
I have:
I removed the chart cache (`rm -rf ~/.cache/up/charts`), then ran `up uxp install` (with no version specified) and observed the proper versioned chart in the cache:
```
🤖 (up) ls ~/.cache/up/charts/ …
```

Cache latest chart with proper version on install and upgrade

---

cmd/up/cloud/controlplane.go
cmd/up/cloud/controlplane/kubeconfig/get.go
cmd/up/cloud/controlplane/kubeconfig/kubeconfig.go
cmd/up/uxp/connect.go
docs/commands.md
internal/kube/client.go

Adds support for merging `kubeconfig` data for a control plane into local `kubeconfig`.
Fixes #86 
All keys in the new `kubeconfig` entries are structured as `upbound-<control-plane-id>`
I have:
Tested the following scenarios:
- Merge into existing default `kubeconfig` and verify that other entries are not overwritten:
```
cat token.txt | up cloud ctp kubeconfig get 7a25b9a5-43a9-474a-a92d-f2afe839095b --token=-
🤖 (up) k get pods -A
NAMESPACE        NAME                                      READY   STATUS    RESTARTS   AGE
upbound-system   crossplane-8644547dfd-ptwwx               1/1     Running   0          3h19m
upbound-system   crossplane-rbac-manager-57b44db5d-xt76w   1/1     Running   0          3h19m
upbound-system   upbound-agent-59f5c67c64-zrrjt            1/1     Running   0 …
```

Support population of kubeconfig files

---

cmd/up/cloud/controlplane/list.go

Updates the control plane table output to include the status of each
control plane.
Fixes #103 
I have:
```
🤖 (up) up cloud ctp list -a dan
NAME      ID                                     SELF-HOSTED   STATUS
testing   a463eb73-c0db-4ff7-b1e5-b4262808c4be   false         ready
🤖 (up) up cloud ctp create two -a dan
🤖 (up) up cloud ctp list -a dan
NAME      ID                                     SELF-HOSTED   STATUS
two       82232a45-595a-4727-acfa-b165900ad6f2   false         provisioning
testing   a463eb73-c0db-4ff7-b1e5-b4262808c4be   false         ready
🤖 (up) up cloud ctp delete 82232a45-595a-4727-acfa-b165900ad6f2
🤖 (up) up cloud ctp delete list -a dan
NAME      ID                                     SELF-HOSTED   STATUS
two …
```

Show status when listing control planes

---

cmd/up/cloud/controlplane/kubeconfig/get.go

Updates the proxy endpoint default to use controlPlanes instead of the
noew deprecated env endpoint.
I have:
Executed same steps as https://github.com/upbound/up/pull/102

Use controlPlanes proxy endpoint as default

---

cmd/up/uxp/common.go
cmd/up/uxp/install.go
cmd/up/uxp/upgrade.go
internal/uxp/installers/helm/helm.go

This PR adds support for installing/upgrading crossplane (or uxp) charts from a local  chart archive or a local directory. The local chart to be processed can be specified with the `--bundle` command-line option.
Note: I'm planning to use the changes in this PR in the demo, and I believe it could prove to be useful for development scenarios. If this functionality is already provided by other means, or if you believe it's not appropriate, we can close this PR.
I have:
Manually tested installing a downloaded UXP chart both from an archive and from a folder containing extracted contents. Also  verified installations & upgrades from a Helm repo still work.

Support for installing/upgrading charts from local files & dirs

---

cmd/up/enterprise/install.go
go.mod
go.sum

Updates the up enterprise install command to create an image pull secret
using the provided license id and token. The image pull secret is
required to fetch the component images included in the enterprise helm
chart.
Fixes #119 
I have:
I used the following command to install a development version of `enterprise` and verified that credentials were created correctly and images were pulled sucessfully.
```
up enterprise install <version> --repo <redacted> --skip-license --set mysql.mysqlUser=upbound --set mysql.mysqlPassword=upbound --set redis.auth.password=supersecret
```

Create image pull secret on enterprise install

---

docs/configuration.md

Removes the cloud subcommand from up logout as it is no longer valid in
the latest releases.
I have:
n/a

Remove cloud from up logout command

---

internal/xpkg/dep/manager/utils.go
internal/xpkg/snapshot/deprecation_test.go
internal/xpkg/snapshot/meta.go
internal/xpkg/snapshot/snapshot.go
internal/xpkg/snapshot/validator.go
internal/xpkg/snapshot/validator/validator.go
internal/xpkg/workspace/meta/meta.go
internal/xpkg/workspace/meta/meta_test.go

Prior to this changeset, when end users would attempt to use `xpls` with a package that was using v1alpha1 of the Configuration or Provider specs a panic would be returned.
Changes made that address this:
- checks were added for the older spec types
- these changes include recognizing the type, updating the type, as well as performing validations on the type
- validationDiagnostics were updated to account for warnings instead of simply errors in order to communicate to the end user that they were using a deprecated version.   
Fixes #131 
I have:
In addition to general functional testing of validations against the reported problematic repo https://github.com/upbound/platform-ref-azure, functional tests were performed to verify:
- the panic no longer is returned when using v1alpha1
- a …

Add support for v1alpha1 Configuration and Provider types

---

docs/configuration.md

Removes a stale reference to an up cloud command and fixes wording of
sentence.
I have:
n/a -- docs

Remove stale reference to up cloud commands

---

internal/xpkg/snapshot/snapshot.go
internal/xpkg/workspace/workspace.go
internal/xpls/server/server.go

Prior to this change, if an end user opened a package in VS Code and the following were true:
* the file that was opened was not the `crossplane.yaml`
* the end user did not have external dependencies loaded in their cache as defined by the crossplane.yaml
There would be no feedback given to the end user. Nothing.
With this change, we now validate the `crossplane.yaml` during the initialization stage and emit diagnostics async so that if the above occurs, the end user will see their `crossplane.yaml` file turn red and a notice will show up in the problems window.
Fixes #136 
I have:
Verified that the expected behavior occurred when working with an empty cache and the file that was open during initialization was not the `crossplane.yaml`.

Validate `crossplane.yaml` as part of initialization

---

internal/xpkg/snapshot/validators.go

The previous error handling in validators.go would result in the validator for the XRD not being registered if the `openAPIV3Schema` object was invalid. Instead the desired behavior is to note that it happened (log it) and move on to trying to register the XRD's validator.
I have:
Verified that diagnostics would render again for a given XRD when an invalid schema definition was presented.
Verified that a warn diagnostic was not returned for the given XRD when an invalid schema definition was presented.

Capture validators for XRD if schema def is broken

---

cmd/up/enterprise/enterprise.go
cmd/up/enterprise/mail.go
cmd/up/enterprise/mail_test.go
cmd/up/enterprise/templates/mail.html
internal/generate.go

Adds `up enterprise mail` **EXPERIMENTAL** command for viewing emails that are stored as `Secret`s in a Kubernetes cluster using a small mail portal provided by a local server.
I have:
Tested this out with a cluster with valid emails as `Secret`s.

Add up enterprise mail command

---

internal/vendor/github.com/crossplane/crossplane/xcrd/crd.go
internal/xpkg/snapshot/validators.go
internal/xpkg/snapshot/xrd_test.go

XRDs do not have a hard requirement that a version has a schema. Given that, the previous implementation assumed that there would be a schema object on every version; which results in a panic when a schema does not exist.
This can also be seen if an end user is typing an XRD from scratch and has not yet defined the schema.
Fixes #160 
I have:
1. Verified that a panic is no longer seen in `xpls` when using the https://github.com/danielinclouds/play_crossplane_plugin repo.
2. Verified that typing up the schema and partially supplying its definition does not result in a panic. Effectively mocking the authoring flow of typing everything individually.

Add nil checks for `schema` when evaluating XRD schema field

---

cmd/up/xpkg/xpextract.go
cmd/up/xpkg/xpextract_test.go
cmd/up/xpkg/xpkg.go
internal/xpkg/dep/resolver/image/mock_fetcher.go
internal/xpkg/dep/resolver/image/resolver_test.go
internal/xpkg/name.go

Adds an xp-extract command that extracts xpkg contents and saves them to
a Crossplane cache compatible format. The logic in this command is
almost identical to that in the Crossplane package manager.
> NOTE: this enables folks who want to pre-populate the Crossplane package cache to have a similar experience as prior to Crossplane v1.7. However, we add this command as EXPERIMENTAL because Crossplane does not make any promises about backwards compatibility for its package cache format.
I have:
`up xpkg xp-extract crossplane/provider-aws:v0.24.1` and verified that `out.gz` contained the correct package contents (decompressed using `gunzip`). Then started Crossplane `v1.7.0` with it in the package cache and used it as a [`Provider` …

Add `up xpkg xp-extract` command as EXPERIMENTAL

---

cmd/up/xpkg/push.go

Adds a NewMultiKeychain for use when performing an `xpkg push`. This approach attempts to use the docker-credentialhelper-up and fallsback to the default docker cred helper if unsuccessful.
Fixes #170 
I have:
```sh
cat ~/.docker/config.json
{
"auths": {
"https://index.docker.io/v1/": {},
"xpkg.dev-deba7a0e.u6d.dev": {}
},
"credsStore": "desktop",
"credHelpers": {
"asia.gcr.io": "gcloud",
"eu.gcr.io": "gcloud",
"gcr.io": "gcloud",
"marketplace.gcr.io": "gcloud",
"staging-k8s.gcr.io": "gcloud",
"us.gcr.io": "gcloud"
}
}
```
./up xpkg push registry.upbound.io/upbound/foo:v0.10.1

Add credential chain fallback for docker-credential-up and `xpkg push`

---

go.mod
go.sum

Fixes #https://github.com/upbound/up/security/dependabot/12
I have:
Ran unit tests.

Update github.com/containerd/containerd to v1.5.10 for dependabot alert

---

cmd/up/xpkg/push.go
cmd/up/xpkg/xpextract.go
cmd/up/xpkg/xpextract_test.go
cmd/up/xpkg/xpkg.go

Updates the experimental up xpkg xp-extract command to support fetching
from a local xpkg file.
I have:
Verified the following commands:
1. Extract from local xpkg implicitly:
```
🤖 (z) ls
package.xpkg
🤖 (z) up xpkg xp-extract --from-xpkg
🤖 (z) ls
out.gz  package.xpkg
```
2. Extract from local xpkg by name:
```
🤖 (z) ls
package.xpkg
🤖 (z) up xpkg xp-extract --from-xpkg package.xpkg 
🤖 (z) ls
out.gz  package.xpkg
```
3. Fail to extract with multiple `--from-*`:
```
🤖 (z) up xpkg xp-extract --from-xpkg --from-daemon package.xpkg 
Usage: up xpkg xp-extract [<package>]
[EXPERIMENTAL] Extract package contents into a Crossplane cache compatible format. Fetches from a remote registry by default.
Arguments:
[<package>]    Name of the package …
```

Supporting extracting contents from local xpkg

---

cmd/docker-credential-up/main.go
cmd/up/controlplane.go
cmd/up/login.go
cmd/up/login_test.go
cmd/up/logout.go
cmd/up/main.go
cmd/up/xpkg/push.go
internal/credhelper/credhelper.go
internal/credhelper/credhelper_test.go
internal/upbound/context.go

Moves all commnon flags and context required to communicate with Upbound
to a common package to be consumed by relevant commands.
Adds support for restricting the domain that the Docker cred helper will
accept. Default behavior is to accept any.
Updates up xpkg push to use UP_DOMAIN with a default of upbound.io. This
means that any upbound.io domain will use the credential helper logic,
while pushing to a registry like dockerhub will fall back to whatever
exists in the Docker config file. Setting UP_DOMAIN will allow using
Upbound credentials to push to other domains, such as a local install of
Upbound.
Fixes #178 
I have: …

Replace `UP_ENDPOINT` with `UP_DOMAIN`

---

cmd/up/xpkg/build.go
cmd/up/xpkg/push.go
internal/xpkg/build.go

Updates xpkg build to support setting a base image, typically a
controller, other than the empty image.
Adds support for a --controller flag to up xpkg build such that provider
packages can be constructed as a single image. This change only supports
fetching the controller image from the local docker daemon, and can only
support building an image for a single architecture at a time. Options
may be expanded based on feedback from incorporating this functionality
into package building workflows.
Modifies up xpkg push to persist non-package layers and modify rather
than replace the existing config file. This ensures that information
such as os/arch are preserved when building …

Support `--controller` in up xpkg build

---

internal/xpkg/name.go

Updates the .up dir to not be absolute to avoid security concerns when
extracting from an archive.
I have:
Built a package with examples and pushed it, verified that they were extracted correctly:
```
🤖 (xpkg-luop) up xpkg build
🤖 (xpkg-luop) ls
composition.yaml  crossplane.yaml  definition.yaml  examples  luop-171d7f5d3a2a.xpkg
🤖 (xpkg-luop) up xpkg push xpkg.upbound.io/dan/luop:v0.0.2
```

Do not use absolute path for .up dir in xpkg

---

cmd/up/xpkg/push.go
go.mod

Adds support for pushing multiple xpkg and an index such that multi-arch
providers can be pushed as single images.
Fixes #185 
I have:
1. Built two controller images and loaded into daemon with `docker buildx build --load`.
2. Built two `xpkg`'s by referencing controllers with `up xpkg build --controller`.
3. Pushed as multi-arch image with `up xpkg push xpkg.upbound.io/dan/test-xpkg:v0.1.0 -f "amd64.xpkg,arm64.xpkg"`.
4. Verified manifest was an index with `crane manifest and that pulling either arch worked correctly.

Add support for pushing multiple xpkg and an index

---

docs/commands.md

Cleans up documentation for control planes commands after the changes to
the control planes API. Drops the attach and token commands, and adds
documentation for the --mcp-experimental flag.
I have:
```
🤖 (up) up ctp -h
Usage: up controlplane <command>
Interact with control planes.
Flags:
-v, --version                      Print version and exit.
--mcp-experimental             Use experimental managed control planes API ($UP_MCP_EXPERIMENTAL).
--domain=https://upbound.io    Root Upbound domain ($UP_DOMAIN).
--profile=STRING               Profile used to execute command ($UP_PROFILE).
-a, --account=STRING               Account used to execute command ($UP_ACCOUNT). …
```

Clean up commands doc after mcp experimental changes

---

cmd/up/controlplane/kubeconfig/get.go
internal/kube/client.go

The control planes proxy API is getting updated to include:
- a version - i.e. `/v1/
- a trailing k8s resource path param - `k8s`
This change accounts for that by:
- updating the default Proxy URL to include the new version
- append the k8s resource path param when building the URL for the kubeconfig.
Fixes xref: #https://github.com/upbound/squad-orchestration/issues/13
I have:
Tested using the following steps:
1. Built a new `up`
2. created an empty kubeconfig file - `touch kubeconfig`
3. set the empty file as the kubeconfig for the terminal session - `export KUBECONFIG=kubeconfig`
4. ran the following command: `./_output/bin/darwin_arm64/up ctp kubeconfig get AE7FB077-C0E0-4F6D-B5C4-40844E6D6A4E --token=not-a-token`
5. verified the corresponding entry had the correct format:
```bash …
```

Update `ctp kubeconfig get` default Proxy URL

---

cmd/up/controlplane/kubeconfig/get.go
internal/upbound/context.go

Construct proxy in the up context to match pattern used by API and
registry, and consume the UP_DOMAIN env var.
Updates to consume the up context proxy domain and sets the account in
the path for the UP_MCP_EXPERIMENTAL config.
I have:
```
$ KUBECONFIG=hello.txt up ctp kubeconfig get 8c9f2f45-4fe1-4f97-b687-88e4d0436696 --token=bye
$ UP_MCP_EXPERIMENTAL=true up ctp kubeconfig get hello --token=hi
$ cat hello.txt
apiVersion: v1
clusters:
- cluster:
server: https://proxy.upbound.io/8c9f2f45-4fe1-4f97-b687-88e4d0436696/k8s
name: upbound-8c9f2f45-4fe1-4f97-b687-88e4d0436696
- cluster:
server: http://proxy.local.upbound.io/v1/my-org/hello/k8s
name: upbound-hello
contexts:
- context: …
```

Construct proxy endpoint in up context

---

cmd/up/controlplane/kubeconfig/get.go

Updates proxy path to includes controlPlanes.
I have:
```
$ KUBECONFIG=hello.txt up ctp kubeconfig get 8c9f2f45-4fe1-4f97-b687-88e4d0436696 --token=bye
$ UP_MCP_EXPERIMENTAL=true up ctp kubeconfig get hello --token=hi
$ cat hello.txt
apiVersion: v1
clusters:
- cluster:
server: https://proxy.upbound.io/controlPlanes/8c9f2f45-4fe1-4f97-b687-88e4d0436696/k8s
name: upbound-8c9f2f45-4fe1-4f97-b687-88e4d0436696
- cluster:
server: http://proxy.local.upbound.io/v1/controlPlanes/my-org/hello/k8s
name: upbound-hello
contexts:
- context:
cluster: upbound-8c9f2f45-4fe1-4f97-b687-88e4d0436696
user: upbound-8c9f2f45-4fe1-4f97-b687-88e4d0436696
name: upbound-8c9f2f45-4fe1-4f97-b687-88e4d0436696
- context:
cluster: upbound-hello
user: upbound-hello …
```

Include controlPlanes in proxy path

---

cmd/up/controlplane/kubeconfig/get.go
internal/kube/client.go

Fixes an issue where /k8s was incorrectly being appended to proxy URL
when not using MCP experimental mode.
I have:
```
🤖 (up) KUBECONFIG=test.yaml up ctp kubeconfig get --mcp-experimental exp-test --token=something
🤖 (up) KUBECONFIG=test.yaml up ctp kubeconfig get e50b0bb0-48e9-4f1a-811b-f6a265c2afa9 --token=something
🤖 (up) cat test.yaml 
apiVersion: v1
clusters:
- cluster:
server: https://proxy.upbound.io/controlPlanes/e50b0bb0-48e9-4f1a-811b-f6a265c2afa9
name: upbound-e50b0bb0-48e9-4f1a-811b-f6a265c2afa9
- cluster:
server: https://proxy.upbound.io/v1/controlPlanes/hasheddan/exp-test/k8s
name: upbound-hasheddan-exp-test
contexts:
- context:
cluster: upbound-e50b0bb0-48e9-4f1a-811b-f6a265c2afa9
user: …
```

Only add /k8s to kubeconfig server if experimental

---

cmd/up/login.go

Fixes regression in up login where user was prompted for username and
password even if a token was provided. These two login methods should be
mutually exclusive.
Fixes #207 
> Note: requires backport to `release-0.12` and patch release.
I have:
`make build` and `up login --token=<user-token>` with a valid user token and verified that I am not prompted for username / password and login is successful.

Do not prompt for username / password if token is provided

---

cmd/docker-credential-up/main.go

up requires that commands provide a scheme in the UP_DOMAIN, but doing
so causes a failure to match to registry domain in docker-credential-up,
meaning that a separate UP_DOMAIN value must be used for up and
docker-credential-up. This corrects that behavior to parse the hostname
from UP_DOMAIN in docker-credential-up and only pass it along as the
domain for matching.
Fixes #191 
I have:
Verified by setting `UP_DOMAIN-https://upbound.io` and pushing successfully using `docker push` with `docker-credential-up` configured in `~/.docker/config.json`.

Only pass domain to docker-credential-up

---

cmd/up/controlplane/list.go
go.mod
go.sum

Updates control plane listing with experimental MCP API with support for
paging. Currently we just max out page size, but we may opt to support
limiting page size and iterating pages in the future via flags.
I have:
Verified that I can successfully list control planes with experimental API:
```
🤖 (up) up login
Username: orgadmin
Password: 
🤖 (up) up ctp list
NAME          ID                                     STATUS
tt-test-001   3fa92104-bfbc-40f0-ac46-81c84579cb34   ready
tt-test-003   6bc0d6aa-7eb0-4723-b26e-1dc50a70c232   ready
```

Update MCP experimental ctp list with paging

---

cmd/up/controlplane/controlplane.go
cmd/up/controlplane/create.go
cmd/up/controlplane/delete.go
cmd/up/controlplane/kubeconfig/get.go
cmd/up/controlplane/list.go
cmd/up/license.go
cmd/up/login.go
cmd/up/login_test.go
cmd/up/logout.go
cmd/up/main.go
cmd/up/uxp/install.go
cmd/up/uxp/uninstall.go
cmd/up/uxp/upgrade.go
cmd/up/xpkg/build.go
cmd/up/xpkg/dep.go
cmd/up/xpkg/init.go
cmd/up/xpkg/push.go
cmd/up/xpkg/xpextract.go
cmd/up/xpkg/xpextract_test.go
go.mod
go.sum
internal/kube/client.go

Supports the -q,--quiet and --pretty flags to allow configuring whether
and how output is emitted globally. Also binds pterm text and table
printers to context for commands to consume as needed.
Moves all commands other than up upbound and xpls to use bound pterm
writers and emit output on success unless supressed.
Fixes #
I have:
Tested commands with updated output:
```
🤖 (up) up ctp list
NAME          ID                                     STATUS
tt-test-001   3fa92104-bfbc-40f0-ac46-81c84579cb34   ready 
tt-test-003   6bc0d6aa-7eb0-4723-b26e-1dc50a70c232   ready 
🤖 (up) up -h
Usage: up <command>
The Upbound CLI
Flags:
-h, --help       Show context-sensitive help.
-v, …
```

Move to pterm, emit success message for all operations, and support `--quiet` and `--pretty` global output config

---

cmd/up/controlplane/controlplane.go
cmd/up/main.go
cmd/up/repository/create.go
cmd/up/repository/delete.go
cmd/up/repository/list.go
cmd/up/repository/repository.go
cmd/up/xpkg/push.go
cmd/up/xpkg/xpextract.go

Adds repository commands for create, list, and delete.
Adds an optional --create flag to up xpkg push to support creating a
repository on push if it does not exist.
Fixes #216 
I have:
```
🤖 (up) up r list
No repositories found in hasheddan
🤖 (up) up xpkg push --create hasheddan/create-on-push:v0.0.1
xpkg pushed to hasheddan/create-on-push:v0.0.1
🤖 (up) up r list
NAME             TYPE            PUBLIC   UPDATED
create-on-push   configuration   false    6s     
🤖 (up) up r delete create-on-push
hasheddan/create-on-push deleted
🤖 (up) up r list
No repositories found in hasheddan
```

Add support for repository management and create on push

---

cmd/up/organization/delete.go
cmd/up/repository/delete.go
cmd/up/robot/delete.go
cmd/up/robot/token/delete.go
cmd/up/xpkg/init.go
cmd/up/xpkg/init_test.go
internal/input/prompt.go

Signed-off-by: Jason Tang <jason@upbound.io>
This PR adds a `--force` option to destructive commands, prompting the user by default to confirm the deletion of the entity (repository, robot, robot token, organization). If `--force` is supplied, no prompt is given.
If the user backs out of the delete, we will return an error, which will show the CLI usage by default.
I hope I know what I'm doing! ; )
Fixes #232 
I have:
Tested commands with and without the `--force` option on dev, except the `org` as I cannot create additional orgs.

Add --force option to destructive commands

---

cmd/up/controlplane/controlplane.go
cmd/up/main.go
cmd/up/robot/robot.go
cmd/up/upbound/upbound.go
cmd/up/xpkg/xpextract.go
cmd/up/xpkg/xpextract_test.go
cmd/up/xpkg/xpkg.go
internal/upbound/context.go

Moves controlplanes and upbound commands under the alpha distinction,
but also maintains hidden location at root in the tree. All
documentation and references will use the `up alpha` variants, but the
hidden commands serve to reserve a future location for these commands,
and, in this case, preserve backwards compatability with commands that
already existed.
up upbound has been moved to the alpha group of commands, signaling that
the entire group is experimental. Because of this, we can drop the
[EXPERIMENTAL] distinction from up upbound mail explicitly.
Moves the up xpkg xp-extract command to alpha group. The previous
location is preserved, but is hidden from the user. …

Move experimental and preview commands to `alpha` group 

---

cmd/up/logout.go
internal/config/config.go
internal/upbound/context.go
internal/upbound/context_test.go

Updates the Upbound Context to include ProfileName such that commands
can specify profile when fetching or updating.
Updates the logout command to correctly identify profile by name rather
than the ID it currently contains.
Updates profile marshaling to emit NONE for session if not present in
order to help users identify whether they shouldn't expect to be
authenticated.
I have:
```
🤖 (up) up login
Username: hasheddan
Password: 
hasheddan logged in
🤖 (up) up profile view
{
"default": {
"id": "hasheddan",
"type": "user",
"session": "REDACTED",
"account": "hasheddan"
}
}
🤖 (up) up logout
hasheddan logged out
🤖 (up) up profile …
```

Fix up logout and hint when session is missing

---

cmd/up/controlplane/controlplane.go
cmd/up/controlplane/kubeconfig/kubeconfig.go
cmd/up/controlplane/pullsecret.go
cmd/up/controlplane/pullsecret/create.go
cmd/up/controlplane/pullsecret/pullsecret.go
cmd/up/main.go
cmd/up/organization/organization.go
cmd/up/profile/config/config.go
cmd/up/profile/profile.go
cmd/up/repository/repository.go
cmd/up/robot/robot.go
cmd/up/robot/token/create.go
cmd/up/upbound/install.go
cmd/up/upbound/upbound.go
cmd/up/upbound/upgrade.go
cmd/up/uxp/uxp.go
cmd/up/xpkg/xpextract.go
cmd/up/xpkg/xpextract_test.go
cmd/up/xpkg/xpkg.go
cmd/up/xpls/xpls.go
internal/feature/maturity.go
internal/kube/apply.go
internal/upbound/token.go
internal/upbound/token_test.go

Restructures alpha level command gating to dynamically hide commands
from help based on the branch they are accessed on. This allows for
tagging commands such that they can be accessible from multiple
branches, but are not shown in the help at maturity levels that differ
from their own.
Also updates to hide the usage help on hidden commands, instead
encouraging folks to use the variant at the specified maturity level. In
the future we will introduce alpha commands and not allow them to be
invoked on the main tree, but for now we want to keep existing commands
functioning properly even though they are not discoverable.
Adds a feature package that allows for specifying the maturity level of
a command.
Signed-off-by: hasheddan …

Add support for `up ctp pull-secret create` and require token create output

---

cmd/up/main.go
docs/commands.md
docs/maturity.md
docs/workflows.md
internal/feature/maturity.go

Updates the HideMaturity method to also consider self such that any
nodes that hide their children will also hide themselves if they do not
match the specified maturity level.
Cleans up workflow documentation by removing unsupported functionality.
Updates the commands doc to reflect that state of commands for v0.13.0.
Adds documentation describing the up command maturity framework and how
commands are migrated to one level of maturity to another.
Fixes https://github.com/upbound/up/issues/237
I have:
Before:
```
🤖 (up) up upbound -h
Usage: up upbound <command>
Interact …
```

Fix top-level alpha command help output and updates docs for v0.13.0 release

---

.github/workflows/promote.yml

The promote workflow complains when using Go 1.17. This updates to match
how we setup Go version in other workflows.
I have:
Will need to be tested post merge.

Set Go version to 1.18 in promote workflow

---

cmd/up/controlplane/controlplane.go
cmd/up/controlplane/create.go
cmd/up/controlplane/delete.go
cmd/up/controlplane/list.go
cmd/up/upbound/profiles.go
docs/commands.md
internal/upbound/context.go
internal/upbound/context_test.go

Drops all conditional API calls as the previously experimental API is
now the only control plane API.
Fixes #255 
I have:
Verified all modified commands execute correctly against `https://api.upbound.io`.

Drop `UP_MCP_EXPERIMENTAL` in favor of new control planes API

---

cmd/up/controlplane/controlplane.go
cmd/up/controlplane/pkg/install.go
cmd/up/controlplane/pkg/pkg.go
cmd/up/upbound/connecting.go
cmd/up/upbound/install.go
cmd/up/upbound/upgrade.go
cmd/up/upbound/watchers.go
hack/boilerplate.go.txt
internal/kube/watch.go
internal/resources/package.go
internal/upterm/styles.go

Adds configuration and provider install commands to the ctp group. The
same struct is used for both commands, but variable interpolation is
used to parameterize based on the subtree from which the command is
invoked.
Fixes #159 
I have:
Verified successful install of providers and configurations, as well as updates to functionality in `up upbound` commands.
```
🤖 (up) kind create cluster
Creating cluster "kind" ...
✓ Ensuring node image (kindest/node:v1.21.1) 🖼
✓ Preparing nodes 📦  
✓ Writing configuration 📜 
✓ Starting control-plane 🕹️ 
✓ Installing CNI 🔌 
✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:
kubectl cluster-info --context kind-kind
Have a question, bug, or feature …
```

Add support for `up ctp provider install` and `up ctp configuration install`

---

docs/commands.md

MCPs are now addressed by name, so the ID references are removed.
I have:
n/a

Clean up remaining mcp ID references in docs

---

internal/xpkg/lint.go
internal/xpkg/parser/linter/linter.go
internal/xpkg/scheme/scheme.go

Adds admission webhooks as valid types in the object scheme for
packages.
Expands provider linter to accommodate admission webhooks.
See upstream commits https://github.com/crossplane/crossplane/commit/6c0afa2be3dfbcfed918aec9e55df16557d99d44#diff-20d88315192c28a14e8d19b9042c1dfbfad06ce54916ab4b387dda1aae5e2894 and https://github.com/crossplane/crossplane-runtime/commit/90b7988df458471e14b868d16f94a5f6c74a338b
Fixes #270 
I have:
Verified that building a provider package with webhook configurations was successful.

Support webhook configurations in provider packages

---

Makefile

This change will cause 'make' to fail if sha256sum is not installed.
Previously if sha256sum was not installed, make would print an error that was easily lost in the output, and the files containing the SHA sums were not created.
This does an upfront check for sha256sum and fails the build if it can't be found. 
I discovered this because sah256sum is not installed on Mac OS by default. 
Note: I could have included image.mk or imagelight.mk to define the binary. I didn't do that because I didn't want to pull all the other irrelevant definitions in those files. Also, this avoided modifying the build submodule and accidentally affecting other builds.
I have:
I ran 'make' multiple times, with and without sha256sum installed.

Fail build if sha256sum is not installed

---

cmd/up/controlplane/controlplane.go
cmd/up/controlplane/get.go
cmd/up/controlplane/list.go

This adds a new command: "ctp get", which shows details of a single control plane. It shows the details as a table with a single row, similar to kubectl. 
I have:
Tested manually. I didn't see tests for most commands, so I followed suit. 
Sample output:
```
up alpha ctp get demo-ucp-idp
NAME           ID                                     STATUS
demo-ucp-idp   ffa9da67-8439-4b7d-a466-e1fb635f6ebe   ready 
```
- Add 'get' for other types (e.g. organizations, robots...)
- Add the ability to output in JSON or YAML, to see more details

Add ctp get command, to show a single control plane.

---

cmd/up/organization/get.go
cmd/up/organization/list.go
cmd/up/repository/get.go
cmd/up/repository/list.go
cmd/up/robot/get.go
cmd/up/robot/list.go
cmd/up/robot/token/get.go
cmd/up/robot/token/list.go

For the org, repo, robot, and robot commands, add support for formatted (json/yaml) output for the get and list commands.
Examples:
```
up org list --format json
[
{
"id": 1,
"name": "upbound",
"displayName": "Upbound Inc",
"creatorId": 0,
"role": "owner",
"reservedEnvironments": 5
},
{
"id": 829,
"name": "upbound-dev",
"displayName": "Upbound Dev",
"creatorId": 0,
"role": "owner",
"reservedEnvironments": 0
}
]
```
```
up org get upbound --format json
{
"id": 1,
"name": "upbound",
"displayName": "Upbound Inc",
"creatorId": 0,
"role": "owner",
"reservedEnvironments": 5
}
```
I have:
This code has been manually tested.

Add formatted ouput for more get & list commands

---

cmd/up/configuration/configuration.go
cmd/up/configuration/get.go
cmd/up/main.go

Add a completion predictor (which support tab complete) for configuration
I have:
Manual testing

Add completion predictor for configurations

---

cmd/up/organization/organization.go
cmd/up/organization/user/deleteinvite.go
cmd/up/organization/user/invite.go
cmd/up/organization/user/listinvites.go
cmd/up/organization/user/listmembers.go
cmd/up/organization/user/removemember.go
cmd/up/organization/user/user.go

Closes https://github.com/upbound/up/issues/285
Adds the following commands:
```
Usage: up organization (org) user <command>
Manage organization users.
Flags:
--format="default"             Format for get/list commands. Can be: json, yaml, default
-v, --version                      Print version and exit.
-q, --quiet                        Suppress all output.
--pretty                       Pretty print output.
--domain=https://upbound.io    Root Upbound domain ($UP_DOMAIN).
--profile=STRING               Profile used to execute command ($UP_PROFILE).
-a, --account=STRING               Account used to execute command ($UP_ACCOUNT).
--insecure-skip-tls-verify     [INSECURE] Skip verifying TLS certificates …
```

Add Organization user management

---

cmd/up/controlplane/controlplane.go
cmd/up/controlplane/list.go
cmd/up/main.go

The alpha variant will now be hidden to maintain compatibility with systems (e.g. CI) that may use it.
`ctp list` and `ctp get` will now also emit basic information about the Configuration that is deployed to them.
I have:
Help on `alpha`:
```
➜  bin ./up alpha -h
Usage: up alpha <command>
Alpha features. Commands may be removed in future releases.
Flags:
-h, --help                Show context-sensitive help.
--format="default"    Format for get/list commands. Can be: json, yaml, default
-v, --version             Print version and exit.
-q, --quiet               Suppress all output.
--pretty              Pretty print output.
Commands:
alpha upbound    Interact with Upbound.
alpha xpkg       Interact with UXP packages.
```
Help on `alpha ctp`:
```
➜  bin ./up alpha ctp -h
Refusing to emit …
```

Move "controlplane" commands to stable maturity level

---

docs/commands.md

Adds missing `controlplane` commands to docs.
I have:

docs: add controlplane commands

---

.gitignore

Ignore direnv's .envrc file. I like to use it to set my PATH to have the version of up that I've built be first in the PATH. 
Fixes #
I have:
I used "git status" to verify that the .envrc file is ignored.

Ignore direnv's .envrc file.

---

docs/commands.md
docs/configuration.md

* Add documentation on the "configuration" group
* Add documentation on the new install-completions command
* Remove documentation on the "upbound" group since it was removed.
* Tweaked documentation on the CLI configuration to distinguish it from the new configurations. 
Note: The only alpha command that was documented was the upbound group, so the entire alpha section was removed. 
I have:
With the markdown viewer in VS Code.

Update docs: add configuration, remove 'upbound'.

---

cmd/up/controlplane/connect.go
docs/commands.md

Robots don't have any permissions when created and they need to be member of a team with the right permissions on a control plane for their token to work for MCP Connector. And currently, this is challenging to require from user since assigning control plane permissions to a team is disabled in the UI. Doing that as part of `up ctp connect` would be almost overreaching, i.e. create team, create robot, assign robot to a team, assign permission to the team, create token. Also, it'd have to create a team for every cluster, which is not an ideal default. On the other hand, user tokens have permission for all control planes the user has access, hence we're using that even if the user points to an org with `--account` flag.
Ideally, we'd like a robot to be created for each cluster but that will …

connect: always create user token if not provided - no creation of robots

---

cmd/up/xpkg/build.go
go.mod
internal/xpkg/build.go
internal/xpkg/build_test.go

Provides options for defining an external auth config extension location and loads that file (defaults to `auth.yaml`).  If the file exists after parsing the crossplane.yaml file it looks for the auth extension meta annotation and gets the group.  Then iterates the crd's and annotates that object with the object annotation providing the auth config file in that crd.  Lints as normal and then re-serializes the package for output in the image.
Fixes #[520](https://github.com/upbound/shimmer/issues/520)
I have:
run `up xpkg build` with `auth.yaml`
```
version: '2023-01-30'
discriminant: spec.credentials.source
sources:
- name: None
docs: |
Ya don't need anything here!
- name: Secret
docs: |
You're going to need some static credentials.
additionalResources:
- type: Secret
ref: …
```

combine xpkg auth ext anno during build

---

cmd/up/controlplane/kubeconfig/kubeconfig.go

Updates the kubeconfig command for control planes to stable.
I have:
```
$ go run ./cmd/up/ ctp kubeconfig get -h
Usage: up controlplane (ctp) kubeconfig get --token=STRING <control-plane-name>
Get a kubeconfig for a control plane.
Arguments:
<control-plane-name>    Name of control plane.
Flags:
--format="default"             Format for get/list commands. Can be: json, yaml, default
-v, --version                      Print version and exit.
-q, --quiet                        Suppress all output.
--pretty                       Pretty print output.
--domain=https://upbound.io    Root Upbound domain ($UP_DOMAIN).
--profile=STRING               Profile used to execute command ($UP_PROFILE).
-a, --account=STRING …
```

Move up ctp kubeconfig get to stable

---

README.md
cmd/up/login.go
go.mod
go.sum
internal/auth/registry.go
internal/install/helm/registry.go
internal/license/dmv.go
internal/upbound/context.go
internal/version/version.go
internal/xpkg/dep/cache/entry.go
internal/xpkg/dep/marshaler/xpkg/marshaler_test.go
internal/xpkg/lint.go
internal/xpkg/meta/meta.go
internal/xpkg/scheme/scheme.go
internal/xpkg/snapshot/snapshot_test.go
internal/xpkg/snapshot/validators.go
internal/xpkg/workspace/workspace_test.go

`up` CLI is still using the old meta API type for `Provider` type which does not have `omitempty` for the `spec.controller` field and this causes it to be initialized with `""` and when Crossplane sees that, it tries to set the corresponding Deployment image to empty string and fails. I'm not entirely sure how we were getting away with this so far.
Fixes https://github.com/upbound/up/issues/321
I have:
Built a provider package and confirmed that when not given, `spec.controller` field does not appear in the built package.

go.mod: update to crossplane v1.6.0

---

cmd/up/controlplane/connect.go
cmd/up/controlplane/kubeconfig/get.go

Description
Two commands were missing tab completion for control planes:
```
up ctp kubeconfig get ...
up ctp connect ...
```
This adds the missing completer.
I have:
Manually

Added tab completion for two control plane commands

---

cmd/up/controlplane/kubeconfig/get.go
internal/kube/client.go

Use a client to verify connectivity before applying a kubeconfig and setting it as the current context. Will not change the current context on a failure.
Fixes #323 
I have:
Bad token:
```
➜  bin ./up ctp kubeconfig get --token="fake token" my-ctp
up: error: the server has asked for the client to provide credentials
```
Good token, non-existent target:
```
./up ctp kubeconfig get --token=`cat my-token` does-not-exist
up: error: the server could not find the requested resource
```
Oops, wrong Upbound organization:
```
./up ctp kubeconfig get --token=`cat my-token` my-ctp     
up: error: the server could not find the requested resource
```
That's the one!
```
➜  bin ./up ctp kubeconfig get --token=`cat my-token` my-ctp -a upbound
Current context set to upbound-upbound-my-ctp
```

Check validity of kubeconfig before applying it

---

cmd/up/xpkg/batch.go
cmd/up/xpkg/push.go
cmd/up/xpkg/xpkg.go
internal/xpkg/build.go
internal/xpkg/layers.go

This PR introduces an `xpkg batch` subcommand to batch process a family of provider packages. The `xpkg build` implementation dumps the built packages onto the file system for `xpkg push` to load them from the filesystem and push them to a package registry. These two subcommands should stay as is with this PR and a new `xpkg batch` command is added that does not need to store the built provider packages in the filesystem. The packages are instead directly pushed to the configured registry. `xpkg batch` has batch processing capabilities to streamline the build process of a family of smaller provider packages. An example invocation for the command looks like:
```
up xpkg batch --service monolith,config,acm,rds,ec2 --family-base-image build-e46f4576/provider-aws --provider-name provider-aws …
```

xpkg batch subcommand to batch process provider packages

---

internal/xpkg/dep/cache/entry.go

Removes the deferred `File.Close` call in `cache.entry.writeObjects` to decrease the # of simultaneously open files and wraps the error returned from `cache.entry.appendToPackageJSON` to provide more context.
I have:
Tested with Go 1.18.10 on a test configuration package with the following command:
```shell
/tmp/up xpkg dep xpkg.upbound.io/upbound/provider-gcp
```
(I've initially observed this issue with `up@v.17.0`, which uses Go `1.18`)

Prevent deferred File.Close and wrap errors while putting CRDs into xpls provider package cache

---

cmd/up/xpkg/build.go
cmd/up/xpkg/dep.go
cmd/up/xpkg/init.go
cmd/up/xpkg/init_test.go
cmd/up/xpkg/xpkg.go
internal/xpkg/dep/manager/manager.go
internal/xpkg/dep/resolver/image/resolver.go
internal/xpkg/snapshot/snapshot.go
internal/xpkg/workspace/workspace.go
internal/xpkg/workspace/workspace_test.go
internal/xpkg/writer.go
internal/xpkg/writer_test.go

This PR adds errors contexts (e.g. filenames) to errors returned in the xpkg commands. Moreover, it removes the TODO in the workspace loader of missing error handling.

[DevEx] xpkg: add error contexts and print & fail on parse errors

---

cmd/up/space/billing/get.go
go.mod
go.sum
internal/usage/clientutil/utils.go
internal/usage/clientutil/utils_test.go
internal/usage/report/aws/aws.go
internal/usage/report/gcs/gcs.go

- Adds AWS support to `up spaces billing get`
Fixes #
https://github.com/upbound/mxe/issues/143
I have:
- Unit tests for clientutil functions
- Manual testing against Upbound test bucket with usage data within it

Add AWS support to `up spaces billing get`

---

cmd/up/space/prerequisites/ingressnginx/ingressnginx.go
cmd/up/space/prerequisites/manager.go
cmd/up/space/prerequisites/providers/helm/helm.go
cmd/up/space/prerequisites/providers/kubernetes/kubernetes.go
internal/resources/controllerconfig.go
internal/resources/package.go
internal/resources/providerconfig.go

- providers (and related components) are required and will be installed
- ingress-nginx is now required and will be installed
This removes some scope creep that was occurring with the `Spaces` install.
I have:
https://github.com/upbound/up/assets/2375126/c8c1729d-1aa6-43a3-b641-6c14c7956897

Introduce additional requirements for the spaces install

---

internal/upterm/styles.go

Move from earlier UX to fonts that represent better on various backgrounds, see screenshots below:
white background:
black background:
Fixes #354 
I have:
Ran through basic init to see what how the text was shown. See screenshots above.

Use default font rather than setting a font that may be too light

---

cmd/up/space/init.go

Pretty much what the summary says, the correct URL is `https://docs.upbound.io/concepts/upbound-spaces`.
I have:
```
./_output/bin/darwin_arm64/up space init --token-file=key.json v0.14.0-23.ga50d1a87
INFO  Required prerequisites met!
INFO  Proceeding with Upbound Spaces installation...
√   [1/3]: Creating pull secret upbound-pull-secret
√   [2/3]: Initializing Space components
√   [3/3]: Starting Space Components
🙌  Your Upbound Space is Ready!
👀  Next Steps 👇
👉 Check out Upbound Spaces docs @ https://docs.upbound.io/concepts/upbound-spaces
```

Update docs link for `up space init` to point to correct URL.

---

cmd/up/space/defaults/defaults.go
cmd/up/space/init.go

Added `--yes` for unattended installation of Spaces and setting defaults for managed Kubernetes.
I have:
Tested against GKE and EKS.

Spaces: add helpers for default and unattended installation

---

cmd/up/space/destroy.go
cmd/up/space/init.go
cmd/up/space/space.go
cmd/up/space/upgrade.go
internal/install/context.go

This is specifically useful for operators working in an airgapped environment.
Unfortunately, given we don't really know what the shape of the pull secret should be, we do our best to prompt for username/password and supply the registry-endpoint value.
Fixes #349 
I have:
1. Ensured that in the default case, installation via `up space init --token-file=key.json version` still works:
```
./_output/bin/darwin_arm64/up space init --token-file=key.json v0.14.0-23.ga50d1a87
❌ cert-manager
Would you like to install them now? [y/N]: Yes
√   [1/5]: Installing cert-manager
√   [2/5]: Installing universal-crossplane
√   [3/5]: Installing ingress-nginx
√ …
```

Allow operators to override the registry and registry-endpoint for a spaces install

---

cmd/up/space/defaults/defaults.go
cmd/up/space/init.go
cmd/up/space/prerequisites/ingressnginx/ingressnginx.go
cmd/up/space/prerequisites/manager.go
go.mod

* Improve detection of Kubernetes providers for Spaces
* Provision public LB on managed Kubernetes
I have:

Spaces: add support for public load balancer

---

cmd/up/space/destroy.go
cmd/up/space/init.go
cmd/up/space/space.go
cmd/up/space/upgrade.go

If the `install.Context` is not provided by the parent command (it isn't, maybe since @branden's billing PR?) we must construct it in the subcommands. Binding there is too late.

cmd/space: fix missing install.Context

---

cmd/up/space/destroy.go
internal/install/helm/helm.go

For Spaces destroy command:
- Remove the `upbound-system` namespace on destroy
- Make the user confirm the delete
I have:
Tested against v0.15.1 with Spaces
```
******************** DESTRUCTIVE COMMAND ********************
****************** DATA-DESTRUCTION WARNING *****************
WARNING  Destroying Spaces is a destructive command that will destroy data and oprhan resources.
WARNING  Before proceeding ensure that Managed Resources in Control Planes have been deleted.
WARNING  All Spaces components including Control Planes will be destroyed.
To proceed, type: "DESTROY CONFIRMED": DESTROY CONFIRMED
```

Space: improve destroy command

---

cmd/up/space/destroy.go
cmd/up/space/flags.go
cmd/up/space/init.go
cmd/up/space/space.go
cmd/up/space/upgrade.go
internal/install/context.go

- move registry logic into central `flags.go`
- add `--registry-username` and `--registry-password`.

space: unify and deduplicate registry flag logic

---

cmd/up/space/destroy.go
internal/install/helm/helm.go
internal/install/helm/helm_test.go

Fixes these errors:
```
up: error: space.destroyCmd.Run(): couldn't find binding of type kubernetes.Interface for parameter 0 of func(kubernetes.Interface, install.Manager) error(), use kong.Bind(kubernetes.Interface)
```
```
up: error: space.destroyCmd.Run(): couldn't find binding of type install.Manager for parameter 1 of func(*kubernetes.Clientset, install.Manager) error(), use kong.Bind(install.Manager)
```
I have:
I ran `up space destroy` and verified that it got past the binding errors.

Use concrete types with destroyCmd.Run() 

---

cmd/up/space/destroy.go

This fixes a small typo in output.
I have:
Ran `up space destroy` and verified that the typo is gone.

Fix typo in up space destroy output

---

cmd/up/space/init.go
cmd/up/space/upgrade.go
go.mod

Check versions for upgrade and downgrade and warn appropriately:
- on downgrade (we don't formally support that yet)
- on skipped minor version upgrade
- on every major version upgrade

space/upgrade: validate versions locally

---

cmd/up/uxp/uxp.go

This PR makes `uxp.installCmd.AfterApply()` create an `*upbound.Context` rather than take it as an arg, since none of its parent commands are binding it.
Fixes #369.
I have:
I verified that `up uxp install` makes it past `uxp.installCmd.AfterApply()`:
```
branden@crateria up % go run ./cmd/up uxp install
up: error: uxp.installCmd.Run(): rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "rbac-manager" in namespace "upbound-system" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "universal-crossplane": current value is "uxp"
exit status 1
branden@crateria up %
```
The above error is expected since I have a kubeconfig for a …

Fix `uxp install` error "couldn't find binding"

---

cmd/up/space/init.go
cmd/up/space/upgrade.go
cmd/up/space/versions.go
cmd/up/space/versions_test.go
cmd/up/xpkg/init.go
go.mod
internal/install/helm/helm.go
internal/install/install.go
internal/version/version.go
internal/xpkg/dep/manager/manager.go
internal/xpkg/dep/resolver/image/resolver.go
internal/xpkg/lint.go
internal/xpkg/snapshot/meta.go

1. `cmd/up/space/version.go`: static semver constraints against the chart
2. `spaces.upbound.io/up-version-constraints` annotation on the chart: constraints against `up`.
Fixes https://github.com/upbound/mxe/issues/190.

spaces: add bidirectional version constraints

---

cmd/up/configuration/create.go
cmd/up/controlplane/connect.go
cmd/up/controlplane/create.go
cmd/up/controlplane/delete.go
cmd/up/controlplane/get.go
cmd/up/controlplane/kubeconfig/get.go
cmd/up/controlplane/list.go
cmd/up/controlplane/pullsecret/create.go
cmd/up/login.go
cmd/up/login_test.go
cmd/up/logout.go
cmd/up/profile/current.go
cmd/up/profile/list.go
cmd/up/profile/profile.go
cmd/up/profile/set.go
cmd/up/profile/view.go
cmd/up/space/destroy.go
cmd/up/space/flags.go
cmd/up/space/init.go
cmd/up/space/upgrade.go
internal/config/config.go
internal/config/config_test.go
internal/credhelper/credhelper.go
internal/credhelper/credhelper_test.go
internal/profile/profile.go
internal/upbound/context.go
internal/upbound/context_test.go
internal/upbound/flags.go

This adds support for profiles that work with a Space.
* `up space init` behaves the same, except it updates the active profile to be a Spaces profile after a successful install, using the kubeconfig it was provided (or default kubeconfig).
* `up space upgrade` and `destroy` build a kubeconfig from the active Spaces profile if `--kubeconfig` and `--kubecontext` flags are not provided. If kube flags are not provided and the active profile is not a Spaces profile, they will exit with an error.
* New command `up profile set space` updates the active profile to be a Spaces profile without needing to install Spaces via `up space init` first. It uses the default kubeconfig and context unless `--kubeconfig` or `--kubecontext` are provided.
* All commands that assume a non-Spaces profile will …

Add Spaces profiles

---

internal/xpkg/build.go

Providers moving from v1alpha1 do not get annotated with the auth configuration.  This change accounts for v1alpha1 and v1 providers annotating the crd with the upbound console config.
Fixes #1298
I have:
Tested locally building v1 and v1alpha1 provider with auth extension file, package was annotated correctly in both cases.

fix auth annotation not being enabled on v1

---

cmd/up/space/versions.go
cmd/up/space/versions_test.go

Prior to this change, we were unfortunately blocking pre-release installations. Maybe in the future, we choose to take a different stance, however today, not being able to install pre-release versions is pretty limiting when working on those earlier versions in conjunction with `up` as well as if we need to get a pre-release fix out to an external consumer.
I have:
Added new tests that cover the use case I ran into. I verified that the tests failed prior to adjusting the constraints in this changeset.

Allow pre-release versions of spaces to be installed and upgraded to

---

cmd/up/controlplane/controlplane.go
cmd/up/controlplane/create.go
cmd/up/controlplane/delete.go
cmd/up/controlplane/get.go
cmd/up/controlplane/list.go
internal/controlplane/cloud/cloud.go
internal/controlplane/cloud/cloud_test.go
internal/controlplane/controlplane.go
internal/controlplane/errors.go
internal/controlplane/options.go
internal/controlplane/space/space.go
internal/controlplane/space/space_test.go
internal/resources/controlplane.go

With Upbound Spaces having been released last month, an obvious short coming was up CLI support for working with a Space. This changeset begins moving in the direction of having consistent support for `up ctp` between Cloud and Spaces by enabling the following actions when using a Space profile:
* Create `up ctp create {name}`
* Delete `up ctp delete {name}`
* Get `up ctp get {name}`
* List `up ctp list`
Of note:
* New clients were added for working with a Space or Cloud.
* Command invocations were simplified by working against given client interface.
I have:
In the cluster:
```bash
kubectl get ctp
No resources found
```
Outside of cluster:
1. No control planes
```bash
./_output/bin/darwin_arm64/up ctp get one
Control plane one not found
```
```bash
./_output/bin/darwin_arm64/up ctp …
```

Introduce support for `up ctp` (create, get, list, delete) against an Upbound Space 

---

cmd/up/controlplane/connector/connector.go
cmd/up/controlplane/connector/install.go
cmd/up/controlplane/controlplane.go

This PR shuffles the subcommands around a little. This is in anticipation of some reworking for `ctp connect`.
This changeset builds on #388. #388 should be merged/reviewed prior to this PR.
I have:
```bash
./_output/bin/darwin_arm64/up ctp --help
Usage: up controlplane (ctp) <command>
Interact with control planes.
Flags:
--format="default"             Format for get/list commands. Can be: json, yaml, default
-v, --version                      Print version and exit.
-q, --quiet                        Suppress all output.
--pretty                       Pretty print output.
--domain=https://upbound.io    Root Upbound domain ($UP_DOMAIN).
--profile=STRING               Profile used to execute command ($UP_PROFILE).
-a, …
```

Move `ctp connect` to `ctp connector install`

---

cmd/up/controlplane/connect.go
cmd/up/controlplane/connect_test.go
cmd/up/controlplane/controlplane.go
cmd/up/controlplane/disconnect.go
cmd/up/controlplane/disconnect_test.go
cmd/up/controlplane/get.go
cmd/up/controlplane/kubeconfig/get.go
cmd/up/profile/set.go
cmd/up/space/init.go
cmd/up/space/space.go
internal/controlplane/cloud/cloud.go
internal/controlplane/space/space.go
internal/controlplane/space/space_test.go
internal/kube/client.go

In order to make it easier to interact with a control plane, we're introducing a new command and bringing back a previous command with different behavior.
`up ctp connect {name}` has been reworked to connect the operators local kubeconfig to the target control plane. From a UX perspective, this means that an operator can simply point to a control plane and easily begin working within it.
`up ctp disconnect` has been introduced to easily allow the operator to switch back to the previous context they were using before initiating the `connect` command. This makes switching between target a control plane and another kubernetes cluster, quick and frictionless.
Fixes #391 
I have:
1. Introduced new tests
2. Captured the below video working against a local space …

Re-introduce `up ctp connect` add `up ctp disconnect`

---

cmd/up/space/prerequisites/uxp/uxp.go

Updating the version of UXP that the `up space init` command will install if there is no previous UXP install in the cluster.
Fixes #392 
I have:
1. Run `up space init`
2. Verified the crossplane image in the cluster:
```bash
kubectl get pods -A -o json | jq '.items[] | {ns:.metadata.namespace, name:.metadata.name,image:.spec.containers[].image}' | grep upbound/crossplane
"image": "upbound/crossplane:v1.13.2-up.2"
"image": "upbound/crossplane:v1.13.2-up.2"
```

Bump the UXP prereq for spaces to v1.13.2-up.2

---

cmd/up/controlplane/connector/connector.go
cmd/up/controlplane/connector/install.go
cmd/up/controlplane/connector/uninstall.go

We'd like to enable operators to install the mcp-connector into App Clusters pointing to a Space control plane. In order to accomplish that, we needed to slightly extend what the current `up ctp connector install` command is doing and allow passing in:
```
--control-plane-secret={secret name}
```
so that an operator can supply the control plane secret.
In addition, we wanted to make it easier to uninstall the mcp-connector. To accomplish this a new subcommand `up ctp connector uninstall` was introduced.
I have:
1. Verify commands exist
```
./_output/bin/darwin_arm64/up ctp connector --help
Usage: up controlplane (ctp) connector <command>
Connect an App Cluster to a managed control plane.
Flags:
--format="default" …
```

MCP Connector support for Spaces

---

cmd/up/controlplane/controlplane.go
cmd/up/main.go
cmd/up/profile/set.go

Ppl try `up controlplane` and wonder whether/how it works with spaces. This PR adds some help texts pointing to spaces profiles and support for spaces in the first place.

up/controlplane: improve help texts for make 'profile set space' discoverable

---

cmd/up/profile/set.go
cmd/up/profile/set_test.go

We check that there is a upbound-system/mxe-controller deployment.
Based on https://github.com/upbound/up/pull/405
Follow-up of https://github.com/upbound/up/pull/400.
I have:
- manually running `up profile set space` against a Space and against a non-Space kube cluster
- added unit tests for happy case and two unhappy cases.

up/profile: check for Spaces on 'up profile set space'

---

CONTRIBUTING.md

This simply removes outdated docs.
Fixes #410 
I have:
I went to the contribution markdown and no longer saw the text.

Remove release notes.

---

cmd/up/controlplane/create.go
go.mod
go.sum
internal/controlplane/cloud/cloud.go
internal/controlplane/cloud/cloud_test.go
internal/controlplane/options.go

Allow for creating a control plane without a configuration for Cloud.
I have:
Tested locally:
```
minerva:~/src/up $ up ctp create -a upbound bh-horcrux --configuration-name=voldemort-prod
bh-horcrux created
minerva:~/src/up $ up ctp create -a upbound bh-darkarts
bh-darkarts created
minerva:~/src/up $ up ctp list -a upbound
NAME               ID                                     STATUS   CONFIGURATION            CONFIGURATION STATUS
bh-horcrux         7b25c5a7-ef21-41fd-972c-15e8512b3784   ready    voldemort-prod           installationQueued
bh-darkarts        fb8dc677-903b-4b17-bfc2-0bf4eb5976aa   ready    n/a                      n/a
```

Bare Control Planes: allow for creating control planes without a config

---

cmd/up/space/prerequisites/providers/helm/helm.go
cmd/up/space/prerequisites/providers/kubernetes/kubernetes.go
cmd/up/space/prerequisites/uxp/uxp.go

With Spaces 1.2.0 a few of the prerequisites had version changes. This updated `up` to target those versions.
I have:
1. Attempted `up space init` and was able to successfully install 1.2.0-rc.1
```
./_output/bin/darwin_arm64/up space init --token-file=key.json "v1.2.0-rc.1" --set account=taylort
INFO  Setting defaults for vanilla Kubernetes (type kind)
❌ cert-manager
Would you like to install them now? [y/N]: Yes
✓   [1/5]: Installing cert-manager
✓   [2/5]: Installing universal-crossplane
✓   [3/5]: Installing ingress-nginx
✓   [4/5]: Installing provider-kubernetes
✓   [5/5]: Installing provider-helm
INFO  Required prerequisites met!
INFO …
```

Update prerequisite versions for spaces 1.2.0

---

internal/migration/importer/import.go

We've had some internal reports of migration not working, with what appears to be a race between attempting to apply resources prior to the APIs being available. This changeset adds a step to wait for the various PackageRevisions to be healthy before moving on.
I have:

Add step to wait for PackageRevisions to be healthy

---

cmd/up/controlplane/connect.go
cmd/up/controlplane/connect_test.go
cmd/up/controlplane/controlplane.go
cmd/up/controlplane/create.go
cmd/up/controlplane/delete.go
cmd/up/controlplane/get.go
cmd/up/controlplane/list.go
cmd/up/profile/set.go
cmd/up/space/destroy.go
cmd/up/space/upgrade.go
internal/controlplane/cloud/cloud.go
internal/controlplane/cloud/cloud_test.go
internal/controlplane/controlplane.go
internal/controlplane/space/space.go
internal/controlplane/space/space_test.go
internal/profile/profile.go
internal/resources/controlplane.go
internal/upbound/flags.go

With Spaces 1.2, 'groups' are introduced. Unfortunately, that means many of the related commands no longer work. This changeset attempts to address that.
Highlevel changes:
- thread groups through connect, create, delete, get, list
- translate -A == --all-groups for list
I have:
1. Update unit test - all pass
2. Ran through various commands called out below
```bash
./_output/bin/darwin_arm64/up ctp get one
Control plane one not found
./_output/bin/darwin_arm64/up ctp get two -g two
Control plane two not found
./_output/bin/darwin_arm64/up ctp list
No control planes found
./_output/bin/darwin_arm64/up ctp list -A
No control planes found
```
```
./_output/bin/darwin_arm64/up ctp create one
one created
```
```
./_output/bin/darwin_arm64/up ctp create two -g two
two created
```
```bash …
```

space subcommands should respect 'groups'

---

internal/xpkg/dep/marshaler/xpkg/marshaler_test.go

Replace `:` in filenames with `_` (affects a single file).
Fixes https://github.com/upbound/up/issues/424
I have:
Unit tests remain unchanged. Only the name of file in the OS filesystem is changed. It is kept with `:` in the in-memory filesystem that is used during tests.

fix(xpkg/test): Replace invalid char in filename

---

cmd/up/migration/export.go
cmd/up/migration/import.go
internal/migration/importer/import.go
internal/migration/importer/resource.go

This PR is a follow up on the problem described in https://github.com/upbound/up/pull/422 during import:
- Do not restore status for base resources
- Otherwise, packages reported as installed/healthy before they were actually processed. 
- No need for restoring status for any other base resources, so, disabled all together.
- Unifies the confirmation dialog as `spaces init` 
- To confirm exporting secrets.
- When preflight checks failed during import.
I have:
1. Create a control plane
2. Stop Crossplane
3. Import
4. Ensure it waits successfully.

Do not restore package statuses and use the same confirmation dialog as spaces init

---

cmd/up/controlplane/connect.go
cmd/up/controlplane/disconnect.go
cmd/up/controlplane/disconnect_test.go
cmd/up/controlplane/kubeconfig/get.go

What is chagned:
1. print what connect and disconnect do, aka switch contexts in the kubeconfig.
2. fix handling of contexts with underscore. This had been broken on disconnect.
Fixes https://github.com/upbound/up/issues/401.

Improve UX of ctp connect+disconnect

---

cmd/up/controlplane/connect.go
cmd/up/controlplane/connect_test.go
cmd/up/controlplane/create.go
cmd/up/controlplane/delete.go
cmd/up/controlplane/disconnect.go
cmd/up/controlplane/disconnect_test.go
cmd/up/controlplane/get.go
cmd/up/controlplane/kubeconfig/connection.go
cmd/up/controlplane/kubeconfig/get.go
cmd/up/controlplane/kubeconfig/kubeconfig.go
cmd/up/controlplane/list.go
cmd/up/space/destroy.go
cmd/up/space/upgrade.go
go.mod
go.sum
internal/controlplane/cloud/cloud.go
internal/controlplane/space/space.go
internal/kube/client.go
internal/profile/profile.go

Use the same code for both commands, and make `up ctp kubeconfig get` work with spaces.
Signed-off-by: Dr. Stefan Schimanski <stefan.schimanski@upbound.com>

Unify 'up ctp connect' and 'up ctp kubeconfig get'

---

.gitignore
cmd/up/common/version.go
cmd/up/main.go
cmd/up/version/fetch.go
cmd/up/version/version.go
go.mod

This PR introduces a feature that, when using the up --version command, displays the version of Crossplane or Universal Crossplane and, if applicable, the version of the Spaces controller.
Fixes #24
I have:
cluster without crossplane/universal-crossplane:
```
up version
Client Version: v0.25.0-rc.0.33.g625bf51.dirty
```
cluster with universal-crossplane:
```
up version
Client Version: v0.25.0-rc.0.33.g625bf51.dirty
Server Version: v1.15.0-up.1
```
cluster with universal-crossplane:
```
up version
Client Version: v0.25.0-rc.0.33.g625bf51.dirty
Server Version: v1.15.0
```
cluster with universal-crossplane and spaces:
```
up version                                                                               
Client Version: v0.25.0-rc.0.33.g625bf51.dirty
Server Version: v1.14.6-up.1
Spaces …
```

feat(cli): version to subcommand and client side versions

---

cmd/up/migration/import.go
cmd/up/migration/import_test.go

Looks like the current regexp for old control plane path only works if controlplane is named as ctp.
This PR fixes the regexp for old controlplane path.
I have:
Unit tests

Fix regexp for old controlplane path

---

go.mod
go.sum

Upgraded go-containerregistry library to v0.19.1 containing the right fix
https://github.com/google/go-containerregistry/pull/1872
Fixes #416
I have:
Run up xpkg build against Docker 1.25

Fix xpkg build against Docker 1.25

---

cmd/up/space/attach.go
cmd/up/space/detach.go

When detaching a space we previously required the space cluster to be available.
This presents a problem is a space cluster is removed before detaching the space.
This PR updates the behavior of `up alpha detach` to allow specifying the name of
the space to detach:
* If a name argument was provided and spaces cluster is available, abort is the
name of the connected space in the cluster doesn't match the provided name.
* If a name argument was provided and spaces cluster is unavailable, delete the
Space and Robot resources in the API and don't attempt to uninstall the agent.
Fixes upbound/squad-upbound-cloud#1347
I have:
Detached a local space after deleting the space cluster.

allow detaching space without a cluster

---

Makefile
cmd/up/space/attach.go
cmd/up/space/detach.go
cmd/up/space/list.go

- **upgrade connect agent version and helm values**
- **always reinstall the agent after attaching**
- **refactor attach/detach flows**
Fixes upbound/connect#179
Additional flows that are enabled by this PR:
This would previously exit without doing anything, instead the flow is now:
```
% up alpha space detach space-bulat-test
INFO  ConfigMap "upbound-system/space-token" not found
WARNING  We're unable to confirm Space "upbound-papper-cutters/space-bulat-test" is currently connected to Upbound Console. Would you like to delete it anyway?
If the other Space cluster still exists, the Upbound agent will be left running and you will need to delete it manually.
▀ Continue? (Y/n) (12s)
INFO  Looking for Robot "upbound-papper-cutters/space-bulat-test"
INFO  Deleting Robot …
```

connect fixes

---

cmd/up/ctx/list.go
cmd/up/ctx/navigation.go

- Use right arrow to select
- Add full vim keybindings support
- Manipulate cursor to select first item below ".." in non-empty lists
- Select ".." by default in empty lists and disable moving the cursor to empty list text
- Prevent full help menu from opening
I have:

Polish keyboard navigation in `up ctx`

---

cmd/up/group/cmd.go
cmd/up/group/create.go
cmd/up/group/delete.go
cmd/up/group/get.go
cmd/up/group/list.go
cmd/up/main.go
internal/config/config.go
internal/profile/profile.go

Rebased on top of https://github.com/upbound/up/pull/457
Add support for `up group create/list/get/delete` using the selected spaces kubeconfig.
I have:
```bash
$ go run ./cmd/up group list
NAME   PROTECTED
$ go run ./cmd/up group create nick-unprotected
nick-unprotected created
$ go run ./cmd/up group create nick-protected --deletion-protection
nick-protected created
$ go run ./cmd/up group list
NAME               PROTECTED
nick-protected     true
nick-unprotected   false
$ go run ./cmd/up group get nick-protected
NAME             PROTECTED
nick-protected   true
$ go run ./cmd/up group delete nick-protected
up: error: group.deleteCmd.Run(): Deletion protection is enabled on the specified group. Use '--force' to delete anyway.
exit status 1
$ go run ./cmd/up group delete nick-protected …
```

Add CRUD support for spaces groups

---

cmd/up/space/prerequisites/providers/helm/helm.go
cmd/up/space/prerequisites/providers/kubernetes/kubernetes.go
cmd/up/space/prerequisites/uxp/uxp.go

- bump uxp version to v1.15.x to use registry feature
- remove registries for provider-helm and provider-kubernetes
Fixes #
I have:
```
_output/bin/darwin_arm64/up space init 1.2.4 --token-file=/Users/haarchri/.aws/spaces-pull.json
INFO  Setting defaults for vanilla Kubernetes (type kind)
❌ cert-manager
Would you like to install them now? [y/N]: Yes
✓   [1/5]: Installing cert-manager                                                                                                  
✓   [2/5]: Installing universal-crossplane                                                                                          
✓   [3/5]: Installing ingress-nginx …
```

feat(uxp): bump uxp to v1.15.x

---

cmd/up/space/detach.go

Attempting to detach a Space without a kubeconfig that points to it (so the agent can be uninstalled) prints a warning and a prompt to proceed anyway: `Continue? (Y/n)`. The capital Y indicates the default is to continue, but pressing Enter aborts. This PR updates the prompt to match the default.
I have:
Tested locally.

Fix detach prompt to match default

---

cmd/up/space/attach.go
cmd/up/space/detach.go

Attach and detach commands use a spinner to communicate the status of the ongoing operation. If a potential conflict is found, such as attaching a Space that's already been attached, the user is prompted to confirm whether they want to proceed. The spinner overwrites that prompt because it's still active, so we work around that by making the spinner draw its own prompt. But the first prompt is briefly visible for a flash, and the spinner's prompt may be misleading about whether the default is to proceed or abort.
This PR updates attach and detach commands to disable the spinner while prompting the user. This relieves the spinner of needing to write its own prompt, allowing attach/detach to use the existing prompt which correctly indicates the default selection.
I have:
I put together a …

Prevent spinner from overwriting confirmation prompt during attach/detach

---

cmd/up/controlplane/controlplane.go
cmd/up/controlplane/list.go
internal/config/config.go
internal/profile/kubeconfig.go
internal/profile/profile.go

This PR makes `up ctp list` kubeconfig context aware, making it independent from the current profile. The profile is automatically derived:
$ kubectl ctx not-space-kube
$ up ctp list
You are not on a space.
$ kubectl ctx space
$ up ctp list
.... controlplanes from the profile matching the kubeconfig context's URL ....
$ up ctp connect ctp
$ up ctp list
In a controlplane, you cannot list controlplanes.
Use 'up ctx ..' to go to group level.
Fixes https://github.com/upbound/spaces/issues/752
NOTE: this breaks the use against a cloud profile. We will bring it back in a follow-up.
I have:
This can be tested locally by running the following setup:
- create local kind cluster with spaces
- create empty kind cluster
- follow the command logic from description

Make ctp list derive context from kubeconfig

---

cmd/up/controlplane/controlplane.go
cmd/up/controlplane/list.go
internal/profile/kubeconfig.go

Reverts upbound/up#457 in favor of https://github.com/upbound/up/pull/471 which contains this code already.

Revert "Make ctp list derive context from kubeconfig"

---

cmd/up/space/features/features.go
cmd/up/space/init.go
cmd/up/space/prerequisites/certmanager/certmanager.go
cmd/up/space/prerequisites/ingressnginx/ingressnginx.go
cmd/up/space/prerequisites/manager.go
cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go
cmd/up/space/prerequisites/providers/helm/helm.go
cmd/up/space/prerequisites/providers/kubernetes/kubernetes.go
cmd/up/space/prerequisites/uxp/uxp.go

Adds [opentelemetry-operator](https://github.com/open-telemetry/opentelemetry-operator) installation as a prerequisite for `space init`, but only if the feature is enabled through the flag.
The operator [needs](https://opentelemetry.io/docs/kubernetes/helm/operator/) `cert-manager` but as it is also installed under prerequisites, we have it covered.
This is needed as the Shared Telemetry needs the operator to provision telemetry collectors for control planes.
Fixes #
I have:
No flag:
```bash
up space init --token-file="../key.json" "v1.2.4" \
--set "account=bob"
INFO  Setting defaults for vanilla Kubernetes (type kind)
❌ cert-manager
Would you like to …
```

space init: install opentelemetry-operator as prerequisite

---

cmd/up/space/attach.go

This PR hides the `up space attach` flag `--robot-token` from help output. Users shouldn't need to provide this flag since robot tokens should be generated for them. And familiarity with other `up` commands might mislead a user into thinking they need to provide a personal access token. This hides the potential stumbling block while keeping it around in case it's helpful for debugging or workarounds.
I have:
I ran `go run ./cmd/up space attach -h` and verified `--robot-token` wasn't in help output.

Hide robot-token flag in attach help

---

Makefile

Bumps the connect agent to the latest version
I have:
attached a space locally and saw everything was working as expected

Bump connect agent version to 0.0.0-408.g343d295

---

cmd/up/main.go

Fixes https://github.com/upbound/up/issues/488
I have:
```
$ ./up help
Usage: up <command>
The Upbound CLI
Flags:
-h, --help                Show context-sensitive help.
--format="default"    Format for get/list commands. Can be: json, yaml, default
-q, --quiet               Suppress all output.
--pretty              Pretty print output.
Commands:
license                Print Up license information.
help                   Show help.
login                  Login to Upbound.
logout                 Logout of Upbound.
configuration (cfg)    Interact with configurations.
controlplane (ctp)     Interact with control planes in the current context, both in the cloud and in a local
Space.
space                  Interact with Spaces.
group                  Interact with groups inside Spaces. …
```

Expose ctx and ctp commands

---

cmd/up/main.go
cmd/up/space/list.go
cmd/up/space/list_test.go
internal/upterm/printer.go

Prior to this changeset, if a user was not logged in to Upbound Cloud they would be presented with the following error when pointed at a disconnected space:
```
up: error: space.listCmd.Run(): failed to get Account "upbound": Unauthorized: {"message":"Unauthorized"}
```
Changes:
- space list is for listing across spaces, which inherently doesn't work in isolation
- update current logic that returns an error if you are not logged in to upbound cloud
- add test coverage for the interactions
- introduce NopPrinters so that we can test logic without needing to account for stdout comms
Relates to https://github.com/upbound/up/issues/487
I have:
New unit tests.
With a local build:
1. Without logging in, attempted command and verified that I received expected message.
``` …
```

up space list against a disconnected space should return message to user

---

cmd/up/group/create.go

This PR removes setting the deletion protection label on groups during create. After the discussion this morning, it was decided this should not be set via the CLI.
Fixes https://github.com/upbound/up/issues/475
I have:
ran `up group create` against a cloud space

Remove deletion protection label/flag from group create

---

cmd/up/ctx/navigation.go

Fixes https://github.com/upbound/up/issues/490
The current logic for setting path to `up` in the Kubeconfig AuthInfo exec switches depending on the target release version. If we are on the `release` build, then use `"up"`. If we are on the `debug` build, then use the current executable path. This has unfortunate side effects when customers use `up` but don't have the CLI in `PATH` - the AuthInfo won't ever be able to resolve the exec.
This change standardises the mechanism regardless of release target. The AuthInfo will always fall back to the full path of the `up` executable, unless we can guarantee we're running it from `PATH`.
I have:
Running from `PATH`:
```yaml
$ up ctx acmeco/upbound-gcp-us-west-1/default --profile production -f -
...
users:
- name: upbound
user:
exec:
apiVersion: …
```

Use `up` in exec if in PATH

---

cmd/up/ctx/list.go
cmd/up/ctx/navigation.go

Update `up ctx` styles and breadcrumb format:
- All purple has been changed to use Upbound brand purple
- The breadcrumbs path now follows the same convention as `up ctx <path>` eg. `upbound/upbound-aws-us-east-1/group/ctp`
Screenshots!
Dark mode
Light mode
I have:
Look at the beautiful screenshots

Update breadcrumbs colors and format

---

cmd/up/ctx/actions.go
cmd/up/ctx/actions_test.go
cmd/up/ctx/cmd.go
cmd/up/ctx/cmd_test.go
cmd/up/ctx/extension_types.go
cmd/up/ctx/list.go
cmd/up/ctx/navigation.go
internal/profile/kubeconfig.go
internal/upbound/kube_context.go

Related to https://github.com/upbound/up/issues/487
Refactor the code for deriving state using the extensions created as part of https://github.com/upbound/up/pull/491
The logic for deriving the state is now:
1. Load the current context, if none found then go to Cloud root navigation
2. Load the extensions
a. If cloud space extension exists, call `DeriveExistingCloudState`
b. If disconnected space extension exists, call `DeriveExistingDisconnectedState`
c. If no extension exists, or extension invalid, call `DeriveNewState`
Each of the `DeriveExisting*State` methods uses the metadata from the extension to load the `Space{}` struct for their navigation state.
In order to get disconnected spaces working, `Space{}` now stores `HubContext` which is a pointer to the context in the current …

Derive state from extensions

---

cmd/up/controlplane/controlplane.go

Fixes https://github.com/upbound/up/issues/503
I have:
```
$ up ./default
Kubeconfig context "kind-spaces-1.4" switched to: Upbound /kind-spaces-1.4/default/
$ up ctp list
GROUP     NAME            CROSSPLANE    SYNCED   READY   MESSAGE   AGE
default   controlplane1   1.14.8-up.1   True     True              141m
```

Fix CRUD on control planes within group scope

---

cmd/up/controlplane/controlplane.go
cmd/up/ctx/cmd.go
cmd/up/group/cmd.go
cmd/up/query/query.go
cmd/up/trace/cmd.go
internal/upbound/kube_context.go

Fixes https://github.com/upbound/up/issues/507
I have:
We can now navigate into and then out of a space
```
$ ./up ctx upbound/upbound-gcp-us-west-1
Kubeconfig context "dev/maincluster" switched to: Upbound upbound/upbound-gcp-us-west-1/
$ ./up ctx .
Kubeconfig context "upbound": Upbound upbound/upbound-gcp-us-west-1/
$ ./up ctx ./default
Kubeconfig context "upbound" switched to: Upbound upbound/upbound-gcp-us-west-1/default/
```

Fix getting stuck in space

---

cmd/up/controlplane/pkg/install.go
cmd/up/ctx/navigation.go
cmd/up/space/destroy.go
cmd/up/space/upgrade.go
cmd/up/trace/cmd.go
internal/upbound/context.go
internal/upbound/flags.go
internal/upbound/kube_context.go
internal/version/version.go

- Update UserAgent to be `up-cli/<version> (<os>; <arch>)`
- Inject user agent into all kube rest clients
- Add TODO to remove any references to the raw client config, where `client.Client` cannot be used
Example user agent: `up-cli/v0.30.0-rc.0.15.g18bb4f5.dirty (darwin; arm64)`
I have:
Running `up ctx <path>` makes multiple calls to spaces, and we can see the requests in the envoy logs:
```json
{"downstreamLocalAddress":"10.88.4.252:8443","downstreamRemoteAddress":"10.138.0.37:0","protocol":"HTTP/1.1","startTime":"2024-05-09T23:03:29.593Z","upstreamHost":"10.96.29.179:8443","userAgent":"up-cli/v0.30.0-rc.0.15.g18bb4f5.dirty (darwin; arm64)","upstreamServiceTime":"14","path":"/api/v1","responseCode":200,"requestId":"","downstreamRequestTTLB":0,"bytesSent":192,"responseHeadersBytes":193,"a …
```

Inject new user agent into all kube rest configs

---

cmd/up/ctx/cmd.go

Previously, using `up ctx . -s` when your kubeconfig is set at a space level would print nothing.
This pull request adds support for `up ctx . -s`:
I have:
```
$ ./up ctx ..
Kubeconfig context "upbound" switched to: Upbound upbound/upbound-aws-us-east-1/
$ ./up ctx . -s
upbound/upbound-aws-us-east-1
```

Support `up ctx . --short` for space

---

cmd/up/space/init.go

Prior to [this change in spaces](https://github.com/upbound/spaces/pull/942), authentication to a control plane supported using the the Kubernetes RBAC of the hub cluster. This meant as long as you used a `cluster-admin` to authenticate to the hub cluster, you could re-use those same credentials to authenticate to any of the control planes. 
After that change, we expect that all authentication would go through Upbound IAM/RBAC by default. As such, ability to use Kubernetes RBAC was changed from opt-out to opt-in (breaking backward compatibility). However, Upbound IAM is only supported after connecting a space to cloud and the workflow for authenticating connected spaces is not yet ready. Therefore users cannot connect to any control planes from a spaces cluster running with the default …

(temp) Enable hub authz and authn by default

---

cmd/up/ctx/list.go
cmd/up/ctx/navigation.go

This PR adds a menu item to the space/group/control plane views that allows users to select it which saves the context and exits, just like q/f10.
Fixes https://github.com/upbound/up/issues/502
I have:
tested locally
screenshots:
Control plane:
Group:
Space:

up ctx: Add menu item for connecting to a control plane

---

cmd/up/ctx/actions.go
cmd/up/ctx/cmd.go
cmd/up/ctx/cmd_test.go

Fixes https://github.com/upbound/up/issues/513
Since we no longer depend on a valid current context, I thought the message that was output when a user switches contexts didn't make sense anymore. It was sometimes even showing `Kubeconfig context "" switched to: ...` which just feels like a mistake. So this PR also updates the output for a successful save and quit to be:
```
$ ./up ctx ./ctp1
Switched kubeconfig context to: Upbound upbound/upbound-aws-us-east-1/default/ctp1
```
The [plan](https://github.com/upbound/up/issues/497) is to eventually rename the exported context to include the group and ctp name, so we would show that instead of the breadcrumbs. But at least this describes that we're adding a new context.
I have:

Fix condition where current context points nowhere

---

cmd/up/ctx/navigation.go

Follow up of https://github.com/upbound/up/pull/510
Fixing nits from comments:
- Removing padding in the line items
- Changing the item text to "Switch context to ..."
I have:

Change up ctx padding and naming

---

cmd/up/group/create.go

Without adding an explicit group label to a namespace, it won't appear in `up group list`. It is confusing to users to run `up group create` and then the namespace not show up in `up group list` because it doesn't have the group label applied. This pull request explicitly adds the label, so that it immediately appears in the list of groups. 
I have:
Tested against disconnected and cloud spaces

Add explicit group label to namespace

---

cmd/up/main.go
go.mod
go.sum

In older versions, the pterm library we use for pretty-printing intercepted SIGINT and SIGTERM. This signal handling was set up in the pacakge's `init` function, so any code that ran before we set up our own signal handler couldn't be killed with Ctrl-C.
The signal handling was removed from pterm in a more recent version (see [1]). Updating to the latest fixes the issue where we couldn't kill `up login` with Ctrl-C (#526).
[1] https://github.com/pterm/pterm/issues/562
Fixes #526
Signed-off-by: Adam Wolfe Gordon <adam.wolfegordon@upbound.io>
I have:
* Manual testing to validate that `up login` can be killed with Ctrl-C at either the `Username` or the `Password` prompt, with or without entering input first.
* `make test` to ensure the dependency update didn't break any unit tests.
* Ran a …

Update pterm so it doesn't intercept signals

---

Makefile
cmd/up/space/attach.go
internal/version/version.go

Without matching account, the attached space rejects every request with 401. This PR checks the account before attaching.

attach: check for upbound-system/mxp-config ConfigMap and check account

---

Makefile
internal/version/version.go

Make `up space attach` work in a dev version.

attach: compile in agentVersion through Go, not Makefile magic

---

cmd/up/query/query.go

Previously, we were binding an `api.Config` to the kong context, when the commands expect a `*rest.Config`. Bind the correct kind of config so that `up alpha query` works as expected.
I have:
Manual verification that `up alpha query` can be used to exercise the query API.

query: Fix kubeconfig fetching in `up alpha query`

---

cmd/up/organization/token.go

Fixes https://github.com/upbound/up/issues/531
Add a new `UP_TOKEN` environment variable that can be used to override the session token present in the current profile.
I have:
Crafting a KUBECONFIG that uses `UP_TOKEN` instead of `UP_PROFILE` works!
```yaml
apiVersion: v1
clusters:
- cluster:
insecure-skip-tls-verify: true
server: https://upbound-aws-us-east-1.space.u5d.dev/apis/spaces.upbound.io/v1beta1/namespaces/default/controlplanes/cbuto-test/k8s
name: upbound
contexts:
- context:
cluster: upbound
extensions:
- extension:
apiVersion: upbound.io/v1alpha1
kind: SpaceExtension
spec:
cloud:
organization: upbound
name: spaces.upbound.io/space
namespace: default
user: upbound
name: upbound
current-context: upbound
kind: Config
preferences: {}
users:
- name: upbound
user:
exec:
apiVersion: …
```

Optionally override of session token in `org token`

---

cmd/up/controlplane/create.go

Add flags to specify the desired Crossplane version and upgrade channel in the
`up ctp create` command. Return an error if a version is specified with a
release channel other than `None`, since the server will accept a spec with a
version specified but ignore it in favor of the release channel's current
version.
For now, we don't have a programmatic way to fetch the valid release channels so
we hard-code the options. Similarly, we don't have an API to fetch supported
versions so we can't list them for the user in the CLI.
Fixes #541
I have:
Manual testing of the following cases:
* `up ctp create` without the new arguments works as before.
* `up ctp create --version=1.14.8-up.1 --channel=None` is successful and the ctp has the right version.
* `up ctp create --version=1.14.8-up.1` throws …

ctp: Allow version and upgrade channel to be specified in create

---

cmd/up/ctx/list.go
cmd/up/ctx/list_test.go
cmd/up/ctx/navigation.go
go.mod
go.sum

In the root/home screen of `up ctx`, include "Disconnected Spaces" alongside the list of cloud organizations. The "Disconnected Spaces" section lists all kubeconfig contexts that contain a Space, as determined by either the spaces extension being present in the config, or the mxp ConfigMap being present in the cluster.
Since the home screen is now available regardless of the user's current kubeconfig context, display a message (rather than an error) if we're unable to list organizations from cloud. This ensures that users who aren't logged in (because they use only disconnected Spaces) can still use `up ctx`.
This also makes it necessary to improve how we handle cursor manipulation in the list view. We programmatically manipulate the cursor in two cases:
1. When constructing the list of …

ctx: Enable navigation between cloud and disconnected Spaces

---

cmd/up/ctx/list.go
cmd/up/ctx/navigation.go

Make it clearer that unselectable items are unselectable by dimming them. We use the same color as the help bar, since it's appropriately subdued.
Also improve the wording for the unselectable message item in empty groups, as suggested by @mattheilman.
I have:
Manual test with an empty group.

ctx: Dim unselectable items and improve wording for empty groups

---

cmd/up/ctx/cmd.go
cmd/up/ctx/cmd_test.go
cmd/up/ctx/list.go
cmd/up/ctx/navigation.go
internal/profile/kubeconfig.go

Use a timeout of 2 seconds when trying to fetch the ingress information for a disconnected Space and attempt to fetch them all in parallel. This should prevent us from hanging forever if a particular kubeconfig context is unreachable or misbehaving. To further help with slow contexts, avoid the overhead of controller-runtime's REST mapping by using the typed client-go client to fetch the ingress ConfigMap.
To make the UI feel more responsive when requests are slow, update the item list asynchronously to the main update loop of the TUI and trigger an update once we have our items. This lets us run a spinner while the items are being updated. As part of this change, switch from generating our own title to using the list widget's built-in title bar, which doesn't change how the TUI looks at …

ctx: Improve performance and make UI more responsive

---

cmd/up/ctx/navigation.go

Similar to our recent change for disconnected Spaces, make the organization view more responsive by looking up all the cloud and connected Space ingresses in parallel.
I have:
Manual testing with the two orgs I'm part of.

ctx: Look up cloud/connected Space ingresses in parallel

---

cmd/up/ctx/navigation.go

Avoid the surprise of seeing different Spaces in the console vs. `up ctx` by listing unreachable items for Spaces that are unreachable or for which we failed to find the ingress. Sort these items to the end of the list so that all the selectable items are at the top.
I have:
Manual testing with organizations that have many unreachable Spaces. Also tested the other menus that may have unselectable items to make sure it all looks good.

ctx: Show unselectable items for unreachable Spaces

---

cmd/up/ctx/cmd.go
cmd/up/ctx/list.go
internal/kube/client.go

Previously, if we hit an error in the `onEnter` function when a user selected an item, we would get stuck completely: the spinner would keep spinning forever. If we hit an error when listing items for a new screen, the error would be displayed but the user wouldn't be able to navigate.
Fix both issues by correctly handling the errors. In both cases, we re-enable the keymap and return the existing model, so the user can continue to navigate.
A glaring example of this issue was if we tried to select a context that was unreachable. We would time out trying to validate the kubeconfig and sit spinning forever. Add a 2 second timeout to the kubeconfig validation to ensure we don't spin for too long, even though we now won't get stuck forever.
I have:
Manual testing with unreachable disconnected …

ctx: Correctly handle errors on selection, including kubeconfig verification timeouts

---

cmd/up/ctx/list.go

Previously, we weren't re-enabling navigation in the happy-path case where we get a new model back from `updateListState`. This didn't prevent navigation from working, since the new model has a new list with a fresh keymap, but it did prevent us from ever disabling nav again, since `navDisabled` was stuck on true.
I have:
Manual testing with both errors and non-error cases.

ctx: Always re-enable nav when updating model

---

cmd/up/ctx/actions_test.go
cmd/up/ctx/cmd.go
cmd/up/ctx/cmd_test.go
cmd/up/ctx/navigation.go
internal/upbound/extension_types.go

Previously, we parsed the ingress URL to determine the name of the Space when
deriving initial state. This was correct for cloud spaces, but not for connected
spaces, since they use a URL starting with `proxy.`.
Add the name of the space to our kubeconfig extension and use it as the space
name when deriving state if it's present. If it's not present, fall back to the
old behavior (in case anyone has a pre-existing kubeconfig with the old
extension in it).
Fixes #557
I have:
Added/updated unit tests to cover the new code paths, and tested manually with cloud, connected, and disconnected Spaces.

ctx: Add space name to kubeconfig extension

---

cmd/up/ctx/writer.go

Fixes https://github.com/upbound/up/issues/562
With some Github searching, I found another project that sets the explicit output path here: https://github.com/kubernetes-sigs/kwok/blob/4f5fb135109ce234d8ccdb185ed041647bc4dd90/pkg/utils/kubeconfig/kubeconfig.go#L129-L132
I have:
```
$ ./_output/bin/darwin_arm64/up ctx upbound/upbound-aws-us-east-1/default/michael-test -f ../here.yaml
Switched kubeconfig context to: Upbound upbound/upbound-aws-us-east-1/default/michael-test
$ ls .. | grep here.yaml
here.yaml
```

Remove default loading rules for explicit paths

---

cmd/up/repository/permission/grant.go
cmd/up/repository/permission/list.go
cmd/up/repository/permission/permission.go
cmd/up/repository/permission/revoke.go
cmd/up/repository/repository.go
go.mod
go.sum

uses https://github.com/upbound/up-sdk-go/pull/94 
add repo permission to grant teams permissions
Fixes #
I have:
```
up repo permission list test123 -a upboundcare                                                
TEAM      REPOSITORY                                 PERMISSION   CREATED                UPDATED
test123   function-conditional-patch-and-transform   write        2024-06-25T06:23:17Z   n/a
```
```
up repo permission revoke test123 function-conditional-patch-and-transform -a upboundcare
Are you sure you want to revoke the permission for team "test123" in repository "function-conditional-patch-and-transform"? This cannot be undone [y/n]: y
Revoking repository permission for team "test123" in repository "function-conditional-patch-and-transform"
Repository permission for team …
```

feat(repo): add repo permissions for teams

---

cmd/up/main.go
cmd/up/space/mirror/mirror.go
cmd/up/space/mirror/spinner.go
cmd/up/space/mirror/static_artifacts.go
cmd/up/space/mirror/types.go
cmd/up/space/space.go
go.mod
internal/oci/oci.go
internal/oci/oci_test.go
internal/oci/values.go
internal/oci/values_test.go
internal/upterm/printer.go

add `up alpha space mirror` command
Fixes #
I have:
```
docker login docker.io/haarchri
docker login xpkg.upbound.io
```
dry-run:
```
up alpha space mirror --version 1.6.0-rc.0.75.gc383bddc --to-dir /tmp/tt      --dry-run
crane pull xpkg.upbound.io/spaces-artifacts/spaces:1.6.0-rc.0.75.gc383bddc /tmp/tt/spaces-1.6.0-rc.0.75.gc383bddc.tgz
crane pull xpkg.upbound.io/upbound/universal-crossplane:1.14.1-up.1 /tmp/tt/universal-crossplane-1.14.1-up.1.tgz
crane pull xpkg.upbound.io/upbound/crossplane:v1.14.1-up.1 /tmp/tt/crossplane-v1.14.1-up.1.tgz
crane pull xpkg.upbound.io/upbound/universal-crossplane:1.14.2-up.1 /tmp/tt/universal-crossplane-1.14.2-up.1.tgz
crane pull xpkg.upbound.io/upbound/crossplane:v1.14.2-up.1 /tmp/tt/crossplane-v1.14.2-up.1.tgz
crane pull …
```

feat(mirror): add alpha space mirror cmd

---

cmd/up/ctx/actions.go
cmd/up/ctx/cmd.go
cmd/up/ctx/navigation.go

The path string printed after every command should be working as argument, i.e. it is supposed like an absolute identifier of a context like a control plane. This was not the case before this PR. Especially the `up ctx . --short` output was its own code path with invalid string generation (e.g. lacking the `disconnected/` prefix).
Fixes: #575

ctx: unify path string

---

cmd/up/ctx/cmd.go

Fix bug in https://github.com/upbound/up/pull/577.
Responsible for https://github.com/upbound/spaces/pull/1387 failing tests.

ctx: fix --short output to print the final state not the original state

---

cmd/up/login/login.go

Unhide the `--token` flag for `up login`. This allows logging in with an Upbound access token. While mostly used by CI/automation, there was no strong reason to hide the flag from users. Note that the `xor` option will ensure you cannot specify a username and a token simultaneously.
I have:
- `up login -h` shows the flag and help string
Login with token:
```
./up login --token=`cat my-upbound-token`
86dd1e7e-xxxx-xxxx-xxxx-a23d090axxx logged in
./up ctp list
GROUP   NAME       CROSSPLANE    SYNCED   READY   MESSAGE   AGE
test    ctp-kine   1.16.0-up.1   True     True              38d
```
Attempt login with mutually exclusive flags
```
./up login -u jastang -t MY_TOKEN
up: error: --username and --token can't be used together
```

Unhide --token flag for login

---

cmd/up/query/query.go
cmd/up/query/run.go
internal/profile/urls.go
internal/upbound/kube_context.go

This PR adds
- a pre-check of the Query API in version v1alpha1 and proper error messages to enable the feature gate or update `up`
- make `up query` work within a controlplane
Requires https://github.com/upbound/up/pull/586.

query+get: improve context awareness

---

cmd/up/space/connect.go
cmd/up/space/disconect.go
cmd/up/space/space.go

- Rename the `up space attach/detach` command to `up space connect/disconnect` with aliases to maintain backward compatibility.
- Update all references to "attach" verbiage to now reference "connect"
I have:

Rename up space attach/detach to up space connect/disconnect

---

cmd/up/query/run.go

Follow-up of https://github.com/upbound/up-sdk-go/pull/104. NoHeaders has no effect anymore.

query/get: remove noHeaders in Query API requests

---

internal/xpkg/dep/manager/utils.go
internal/xpkg/dep/marshaler/xpkg/marshaler.go
internal/xpkg/scheme/scheme.go
internal/xpkg/snapshot/meta.go
internal/xpkg/workspace/meta/meta.go
internal/xpkg/workspace/workspace.go

Previously, running `up xpkg dep` in a package containing compositions that use functions would produce an error: `resources in Composition are malformed`. Simiarly, `up xpls` would panic when started on a package with function dependencies.
Update the metadata parser to support function dependencies and the composition parser to support pipelines so that `up xpkg dep` and `up xpls` have at least basic functionality when using functions. Providing useful validation of function pipelines is left as future work.
I have:
~- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.~
Local testing with [configuration-getting-started](https://github.com/upbound/configuration-getting-started).

xpkg: Support function dependencies

---

cmd/up/controlplane/controlplane.go
internal/controlplane/controlplane.go
internal/controlplane/space/space.go
internal/controlplane/space/space_test.go
internal/resources/controlplane.go

With Spaces v1.6.0 we did the following changes in the control plane resource affecting the get and list command outputs:
- We no longer show `SYNCED` column, and show a new `HEALTHY` column instead.
- We store the `MESSAGE` in `status.message` rather than `internal.spaces.upbound.io/message` annotation.
This PR adapts the up cli accordingly.
This was found as a bug in the last LBOP session.
I have:
```
❯ kubectl get ctp
NAME    CROSSPLANE    READY   HEALTHY   MESSAGE                                                              AGE
test    1.15.3-up.1   True    False     Provisioning failed: cannot setup control plane API: cannot pro...   29m
test2   1.15.3-up.1   True    True
❯ go run ./cmd/up ctp list
GROUP     NAME    CROSSPLANE    READY   HEALTHY   MESSAGE …
```

Show healthy column and read message from status for CTP list/get commands

---

install.sh

Removes the trailing "\n" from this output:
```
Up downloaded successfully!
By proceeding, you are accepting to comply with terms and conditions in https://licenses.upbound.io/upbound-software-license.html
Run the following commands to finish installation:
sudo mv up /usr/local/bin/
up version
Visit https://upbound.io to get started. 🚀
Have a nice day! 👋\n                               <==================
```
I have:
N/A

Remove ineffective trailing "\n"

---

CONTRIBUTING.md

Turns out that according to the semver [spec](https://semver.org/#spec-item-9) sorting results in `1.0.0-1 < 1.0.0-rc.1`, so we switch to `-0.rc.1` so that it results in correctly sorting them `1.0.0-0.rc.1 < 1.0.0-1`.
Added reference to internal documentation about cache invalidation.
I have:
N.A.

docs: use -0.rc as tag to fix sorting and mention cache invalidation

---

cmd/up/query/run.go

Fixes https://github.com/upbound/up/issues/599.
I have:
Manually running the command from the issue:
```
go run github.com/upbound/up/cmd/up alpha query providers,providerrevision
NAME                                      INSTALLED   HEALTHY   PACKAGE                                                  AGE
provider.pkg.crossplane.io/provider-nop   True        True      xpkg.upbound.io/crossplane-contrib/provider-nop:v0.2.1   17d
NAME                                                           HEALTHY   REVISION   IMAGE                                                    STATE    DEP-FOUND   DEP-INSTALLED   AGE
providerrevision.pkg.crossplane.io/provider-nop-ecc25c121431   True      1          xpkg.upbound.io/crossplane-contrib/provider-nop:v0.2.1   Active                               17d
```

fix(up/query): print right kind with multiple resources

---

cmd/up/space/mirror/config.yaml

Starting with Spaces v1.17.0, we would like to remove the mxp-authz-webhook Chart. This PR adds the version constraint `<=1.6.x` on the `xpkg.upbound.io/spaces-artifacts/mxp-authz-webhook` & `xpkg.upbound.io/spaces-artifacts/mxp-authz-webhook-openssl` images so that starting from Spaces v1.17.0, they will no longer be mirrored.
I have:

Add a version constraint for the mxp-authz-webhook Chart's images

---

internal/logging/klog.go
internal/upbound/context.go

Pick of https://github.com/upbound/up-private/pull/41.

Less verbose logging

---

cmd/up/space/connect.go
cmd/up/space/disconect.go
internal/version/version.go

Now that spaces images moved into xpkg registry, install agent from there too.
I have:
Created a space in kind and connected it, checked the images afterwards:
```bash
kubectl get pod -A -o json | jq '[.items[] | .spec.containers[] | .image] | sort | unique'
[
"docker.io/kindest/kindnetd:v20240813-c6f155d6",
"docker.io/kindest/local-path-provisioner:v20240813-c6f155d6",
"quay.io/jetstack/cert-manager-cainjector:v1.11.0",
"quay.io/jetstack/cert-manager-controller:v1.11.0",
"quay.io/jetstack/cert-manager-webhook:v1.11.0",
"registry.k8s.io/coredns/coredns:v1.11.1",
"registry.k8s.io/etcd:3.5.15-0",
"registry.k8s.io/ingress-nginx/controller:v1.8.1@sha256:e5c4824e7375fcf2a393e1c03c293b69759af37a9ca6abdb91b13d78a93da8bd",
"registry.k8s.io/kube-apiserver:v1.31.0", …
```

install agent from the spaces registry

---

cmd/up/controlplane/controlplane.go
internal/controlplane/controlplane.go
internal/controlplane/space/space.go
internal/controlplane/space/space_test.go

We recently dropped the healthy column from `kubectl get ctp` output in favor of more detailed messages. This PR does the same with the up ctp get/list commands.
I have:
Before:
```
❯ up ctp list -A
GROUP     NAME   CROSSPLANE    READY   HEALTHY   MESSAGE     AGE
another   ctp2   1.16.2-up.2   True    True      Available   7m38s
default   test   1.16.2-up.2   True    True      Available   9m29s
❯ up ctp get test
GROUP     NAME   CROSSPLANE    READY   HEALTHY   MESSAGE     AGE
default   test   1.16.2-up.2   True    True      Available   9m35s
```
After:
```
❯ go run ./cmd/up ctp list -A
GROUP     NAME   CROSSPLANE    READY   MESSAGE     AGE
another   ctp2   1.16.2-up.2   True    Available   5m17s
default   test   1.16.2-up.2   True    Available   7m8s
❯ go run ./cmd/up ctp get test
GROUP …
```

Drop healthy column from the up ctp get/list

---

cmd/up/space/mirror/config.yaml

We're planning to bump vector.dev dependency in spaces `v1.8` to `0.41.1-distroless-libc` to support workload identity federation in AKS clusters. This PR updates that dependency for `up space mirror`.
The image `xpkg.upbound.io/spaces-artifacts/vector:0.41.1-distroless-libc` has already been mirrored.
I have:

Bump spaces dependency xpkg.upbound.io/spaces-artifacts/vector to 0.41.1-distroless-libc

---

cmd/up/ctx/actions_test.go
cmd/up/ctx/navigation.go

Previously, when connecting to a disconnected space (or a group in a disconnected space), we used the hub context's apiserver address and auth for the returned context. We would like to make some APIs (e.g., query API) available only via the ingress, so we want to use the ingress address for all contexts regardless of whether spaces are disconnected, connected, or cloud.
I have:
~- [ ] Added `backport release-x.y` labels to auto-backport this PR, as appropriate.~
Updated unit tests, manual testing with disconnected and cloud spaces.

ctx: Always use the spaces ingress

---

.github/workflows/ci.yml
.golangci.yml
Makefile
cmd/up/space/connect.go
cmd/up/space/mirror/mirror.go
cmd/up/team/get.go
cmd/up/xpkg/batch.go
cmd/up/xpkg/push.go
go.mod
go.sum
internal/xpkg/snapshot/composition.go

Spaces dropped `mxp-config` configmap, but `up space attach` still looks for it to validate a spaces installation. 
This PR fixes that by using the replacement configmap, namely `spaces-config`, that is available for a couple of releases.
I have:
Tested with a local spaces installation and verified that it can fetch the account information from the new configmap.

Use spaces-config configmap to validate spaces in up space attach

---

cmd/up/xpkg/batch.go

This PR introduces a cli option for `xpkg batch` command to add suffix for provider name during pushing the packages. 
Suffix for provider name during pushing the packages. This suffix is added to the end of the provider name. If there is a service name for the corresponded provider, then the suffix will be added to the base provider name and the service-scoped name will be after this suffix.  Examples: provider-family-aws-suffix, provider-aws-suffix-s3. There is also an env var for this cli option: `PROVIDER_NAME_SUFFIX_FOR_PUSH`.
I have:
Tested locally:
```
make PROVIDER_NAME_SUFFIX_FOR_PUSH=<suffix> SUBPACKAGES="config cloudplatform" BRANCH_NAME=main XPKG_REG_ORGS=xpkg.dev-deba7a0e.u6d.dev/upbound VERSION="v1.8.0-up-test" publish
15:28:34 [ .. ] Batch processing smaller provider …
```

Introduce a cli option to add suffix for provider name during pushing the packages
