README.md

Updates the crossplane upgrade instruction to use the upgrade instead of
install command.
I have:
Executing `up uxp upgrade <version>` with Crossplane installed.

Fix crossplane upgrade instruction in README.md

---

go.mod
go.sum

Updates crossplane-runtime to v0.14.0 to pick up new package parser
functionality.
See https://github.com/crossplane/crossplane-runtime/pull/268 for more info.
I have:
`make build` and tested against packages such as `platform-ref-aws`.

Update crossplane-runtime to v0.14.0

---

cmd/up/cloud/login.go
cmd/up/cloud/login_test.go
go.mod
go.sum

Updates the library used for interacting with JWTs as the previously
used package contains a vulnerability and is no longer maintained. Note
that the vulnerability is not particularly impactful in this tool
specifically, but we prefer to go ahead and move to a package that is
actively maintained.
See CVE-2020-26160.
I have:
Tested manually with `login` features.

Migrate from github.com/dgrijalva/jwt-go to github.com/golang-jwt/jwt

---

cmd/up/xpkg/xpextract.go
cmd/up/xpkg/xpextract_test.go

Adds an option to allow extracting package contents from Docker daemon.
I have:
`docker pull registry.upbound.io/crossplane/provider-aws:v0.24.1` then `up xpkg xp-extract crossplane/provider-aws:v0.24.1 --from-daemon` and verified `out.gz` worked correctly when pre-populating Crossplane package cache.

Support extracting contents of package in daemon

---

docs/commands.md

Updates docs to encompass all recently added commands.
I have:
n/a -- docs

Update docs with full command list

---

cmd/up/logout.go

Updates the logout command to remove the token from the specified config
profile after it is successfully invalidated. This makes it obvious that
a token is no longer valid, and allows for surfacing more accurate
errors if a user attempts to access resources after logout.
I have:
Tested this locally by running `up login` and verifying that config is populated:
```
🤖 (up) cat ~/.up/config.json | jq .
{
"upbound": {
"default": "default",
"profiles": {
"default": {
"id": "hasheddan",
"type": "user",
"session": "<token-omitted>",
"account": "hasheddan"
}
}
}
}
```
Then verified that running `up logout` causes the token to be removed:
```
🤖 (up) cat ~/.up/config.json | jq .
{
"upbound": {
"default": "default",
"profiles": {
"default": { …
```

Clear token from config if logout successful

---

README.md
docs/commands.md

Adds `docker-credential-up` to `README.md` and expands a bit on how `up xpkg` commands function.
Fixes https://github.com/upbound/up/issues/172
I have:
Executed added and updated commands and verified working as advertised.

Add `docker-credential-up` information to README.md

---

cmd/up/xpkg/build.go

Adds suppport for --output on xpkg build and deprecates support for
--name. If neither flag is given, the package directory is used as
output location and the name is generated (metadata.name plus hash),
which matches existing behavior. Command errors if both --name and
--output are supplied. If --output is supplied it is used verbatim after
cleaning path (i.e. there is no generated file name and the .xpkg
extension is not automatically added).
Fixes #184 
I have:
Tested all scenarios described with `platform-ref-aws`:
```
🤖 (platform-ref-aws) up xpkg build --name package.xpkg --ignore ".github/workflows/*,examples/*,hack/*"
🤖 (platform-ref-aws) ls
cluster  cool  crossplane.yaml  database  development.md  docs  examples  hack …
```

Add support for --output on xpkg build and deprecate --name

---

.github/workflows/ci.yml
.github/workflows/promote.yml

The v2 AWS CLI requires setting the region when interacting with S3.
This adds it to all relevant CI steps.
I have:
Observed this working multiple other pipelines (example: https://github.com/crossplane/crossplane/pull/3153)

Set AWS_DEFAULT_REGION to fix AWS CLI upgrade

---

docs/commands.md

Updates commands docs to use upbound group, which has replaced
enterprise.
I have:
n/a -- docs

Update commands docs to reflect new upbound group

---

cmd/up/main.go

Signed-off-by: Aditya Sharma <git@adi.run>
Updates the TODO comment regarding k8s auth plugins
I have:

Update comment about auth plugins

---

README.md

This PR adds [Nix](https://nixos.org) installation instructions for the Upbound CLI to the main README. That's being added to Nixpkgs in [this PR](https://github.com/NixOS/nixpkgs/pull/186452). This PR is currently a draft as it shouldn't be merged until that lands.
I have:

Add Nix installation instructions

---

cmd/up/main.go
cmd/up/organization/create.go
cmd/up/organization/delete.go
cmd/up/organization/list.go
cmd/up/organization/organization.go
go.mod
go.sum

Adds support for organization management commands:
- `up org create <name>`
- `up org delete <name>`
- `up org list`
> Note: we are opting not to support an `up org update` command for now as currently only the display name can be changed and it is unclear whether that will remain the case in the future.
Fixes #223 
I have:
```
🤖 (up) up org list
NAME                 ROLE  
upbound              owner 
crossplane           owner 
dan                  owner 
...
🤖 (up) up org delete dan
dan deleted
```

Add support for organization management commands

---

cmd/up/main.go
cmd/up/robot/create.go
cmd/up/robot/delete.go
cmd/up/robot/list.go
cmd/up/robot/robot.go
cmd/up/robot/token/create.go
cmd/up/robot/token/delete.go
cmd/up/robot/token/list.go
cmd/up/robot/token/token.go
go.mod
go.sum

Adds commands to support create / delete / list of robots.
Adds commands for create / delete / list of robots.
Fixes https://github.com/upbound/up/issues/215
I have:
```
🤖 (up) up robot list -a dan
NAME       ID                                     DESCRIPTION   CREATED
cool-bot   baf29497-bf22-4b0d-81af-7ee692c474d8                 7h27m  
🤖 (up) up robot delete cool-bot
up: error: robots are not currently supported for user accounts
🤖 (up) up robot delete cool-bot -a dan
dan/cool-bot deleted
🤖 (up) up robot create super-cool-bot -a dan
dan/super-cool-bot created
🤖 (up) up robot list -a dan
NAME             ID                                     DESCRIPTION   CREATED …
```

Support robot management commands

---

docs/configuration.md

Updates the configuration documentation to expand on how profiles are
used and include base config / commands to interact with it.
I have:
Verified commands mentioned in the documentation.

Update configuration docs to include base config

---

cmd/up/main.go

Updates usage output to use compact format.
Fixes #250 
I have:
Before:
```
🤖 (up) up -h
Usage: up <command>
The Upbound CLI
Flags:
-h, --help       Show context-sensitive help.
-v, --version    Print version and exit.
-q, --quiet      Suppress all output.
--pretty     Pretty print output.
Commands:
license
Print Up license information.
login
Login to Upbound.
logout
Logout of Upbound.
controlplane (ctp) <command>
Interact with control planes.
organization (org) <command>
Interact with organizations.
profile <command>
Interact with Upbound profiles.
repository (repo) <command>
Interact with repositories.
robot <command>
Interact with robots.
uxp <command>
Interact with UXP.
xpkg <command>
Interact with UXP packages.
xpls <command> …
```

Use compact usage output

---

cmd/up/organization/get.go
cmd/up/organization/organization.go
cmd/up/repository/get.go
cmd/up/repository/list.go
cmd/up/repository/repository.go
cmd/up/robot/get.go
cmd/up/robot/robot.go
cmd/up/robot/token/get.go
cmd/up/robot/token/token.go

Added the following commands:
```
up org get ...
up repo get ...
up robot get ...
up robot token get ...
```
I have:
Manual testing, similar to other commands.

Added get commands for orgs, repos, robots, and robot tokens

---

cmd/up/controlplane/connect.go
internal/install/helm/helm.go

Otherwise users may be misled to believe the APIs are ready as soon as the command completes, which is not the case.
I have:
Manually.

connect: wait for helm installation to complete

---

CONTRIBUTING.md
README.md

Add a contribution guide with release process.
Fixes #64 
I have:
N/A

add contribution guide that includes release process

---

cmd/up/space/prerequisites/ingressnginx/ingressnginx.go

- previous values didn't work well with kind
- updated values based off of upstream kind template
- adjust readiness check for ingress-nginx-controller deploy
I have:
1. Started kind cluster.
2. Deployed spaces to it:
```
./_output/bin/darwin_arm64/up space init --token-file=key.json v0.14.0-rc.0.129.g29db6bd1
❌ cert-manager
Would you like to install them now? [y/N]: Yes
√   [1/5]: Installing cert-manager
√   [2/5]: Installing universal-crossplane
√   [3/5]: Installing ingress-nginx
√   [4/5]: Installing provider-kubernetes
√   [5/5]: Installing provider-helm
INFO  Required prerequisites met!
INFO  Proceeding with Upbound Spaces installation...
√ …
```

Adjust ingress-nginx deployment to target kind

---

cmd/up/space/prerequisites/providers/helm/helm.go
cmd/up/space/prerequisites/providers/kubernetes/kubernetes.go
cmd/up/space/prerequisites/uxp/uxp.go

This is a backport of https://github.com/upbound/up/pull/418 for release-0.22.
I have:
CI

[0.22 backport] Update prerequisite versions for spaces 1.2.0

---

go.mod
go.sum

Switch to a newer patch version of the docker/docker dependency to fix the following CVE: https://github.com/advisories/GHSA-jq35-85cj-fj4p
Fixes #
I have:

bump docker/docker dep to v20.10.27

---

cmd/up/controlplane/connect.go
cmd/up/controlplane/connect_test.go

connect: gracefully handle different context names

---

CONTRIBUTING.md

There is nothing to do in this step.

CONTRIBUTING.md: remove empty release step

---

CONTRIBUTING.md

Signed-off-by: Dr. Stefan Schimanski <stefan.schimanski@upbound.com>

CONTRIBUTING.md: cosmetics

---

install.sh

switch to up version in install script
Fixes #
I have:

fix(script): switch to up version for install script

---

CONTRIBUTING.md

CONTRIBUTING.md: clarification and fixes

---

cmd/up/ctx/navigation.go

Only show groups, not all namespaces.

ctx: filter namespaces by group label

---

pkg/migration/exporter/export.go

Sometimes while resources are being created or deleted, we could hit the following errors:
```
cannot export resources for "defaultsecuritygroups.ec2.aws.upbound.io": cannot fetch resources: cannot list "defaultsecuritygroups.ec2.aws.upbound.io" resources: the server could not find the requested resource
```
Or:
```
cannot get GVR for "dnstxtrecords.network.azure.upbound.io": cannot get REST mapping for "dnstxtrecords.network.azure.upbound.io": no matches for kind "DNSTXTRecord" in version "network.azure.upbound.io/v1beta1"
```
Or:
```
cannot fetch CRDs: cannot list CRDs: an error on the server ("dial tcp 10.96.125.164:443: connect: connection refused") has prevented the request from succeeding (get customresourcedefinitions.apiextensions.k8s.io)
```
Or connection refused errors which we …

fix: exporter retrying on transient errors

---

.github/workflows/ci.yml

Configure Codecov token in order to unblock unitests. 
Fixes # https://github.com/upbound/platform-core/issues/1347
I have:
n/a

configure CODECOV_TOKEN

---

cmd/up/ctx/cmd.go
cmd/up/ctx/cmd_test.go
cmd/up/ctx/navigation.go

Previously we were using the `org` claim inside the auth info token to determine the org name in `DeriveState`. Since moving to use `exec` instead of a raw token, we don't have a token to query. This workaround pulls the name of the organization from the exec env variables list. It's a hack that should be replaced by use of Kubeconfig extensions, which should also replace some other pains and workarounds we've been using in `up ctx`
I have:
`up ctx ..` inside a control plane now resolves to the group level, which implies that the code was able to detect the organization in `DeriveState`

Pull organization name from exec directly

---

cmd/up/ctx/cmd.go

Fixes https://github.com/upbound/up/issues/501
```
$ ./up ctx . -s
upbound/upbound-gcp-us-west-1/craigs-group
```
I have:

Include organization name in `up ctx . --short`

---

cmd/up/controlplane/connect.go
cmd/up/controlplane/kubeconfig/get.go

Fixes https://github.com/upbound/up/issues/484
I have:

Fix legacy redirect errors to include organization in path

---

README.md

Various cleanup fixes to the README file:
- Add command to install latest build version from main branch
- Remove outdated information and broken links
- Remove usage commands in favor of pointing to docs.upbound.io
I have:
Markdown Preview

Cleanup README file

---

cmd/up/space/prerequisites/providers/helm/helm.go
cmd/up/space/prerequisites/providers/kubernetes/kubernetes.go

Bumps provider-kubernetes and provider-helm to newest versions that include MR metrics and upbound identity authentication.
I have:
built local binary and did `up space init`, checked that the providers are in the expected version, created and deleted a Controplane to make sure all works ok.

Bump providers to newest versions

---

cmd/up/space/prerequisites/opentelemetrycollector/opentelemetrycollector.go

Adds a wait on the installation step of the OpenTelmetry Operator for the operator pod to be ready.
This fixes the issue in #548 which was failing the Spaces installation as the webhook was not ready to review the Space level OpenTelemetryCollector resource.
Fixes #548 
I have:
locally built binary with `make` and then ran `up space init`
```bash
_output/bin/darwin_arm64/up space init --token-file="../key.json" "v1.4.0-rc.0.331.g417a41db" \
--set "account=bob" \
--set "features.alpha.observability.enabled=true"
INFO  Setting defaults for vanilla Kubernetes (type kind)
❌ cert-manager
❌ opentelemetry-operator
Would you like to install them now? [y/N]: …
```

Obervability: Wait for OpenTelemetry operator pod to be ready

---

cmd/up/query/get.go

Same as #540, but for `up alpha get` instead of `up alpha query`.
I have:
Still couldn't make it run locally for other reasons, but the error I had changed.

fix(query): fix kubeconfig injection in up alpha get

---

cmd/up/main.go
cmd/up/team/create.go
cmd/up/team/delete.go
cmd/up/team/get.go
cmd/up/team/list.go
cmd/up/team/team.go
go.mod
go.sum

implement teams cmd in up-cli
Fixes #
I have:
tested the implementation from up-sdk-go with an implementation in up-cli 
added in go.mod
cat go.mod
```
[...]
replace github.com/upbound/up-sdk-go => ../up-sdk-go
```
```
up team create test-implementation -a upboundcare
upboundcare/test-implementation created
```
```
up team get test-implementation -a upboundcare   
NAME                  ID                                     CREATED
test-implementation   f68ca5fd-4a83-40bb-a620-3db3da3c9109   17s
```
```
up team list -a upboundcare
NAME                                       ID                                     CREATED
test123                                    5e8e8dab-3598-4003-a5ba-34a12859d60f   23m
test-implementation                        f68ca5fd-4a83-40bb-a620-3db3da3c9109   31s …
```

feat(teams): implement teams cmd

---

cmd/up/robot/robot.go
cmd/up/robot/team/join.go
cmd/up/robot/team/leave.go
cmd/up/robot/team/list.go
cmd/up/robot/team/team.go
go.mod
go.sum

uses https://github.com/upbound/up-sdk-go/pull/93
implements an option to assign an robot to a team 
Fixes #
I have:
```
up robot team list chris -a upboundcare
TEAMS
test678
```
```
up robot team join test123 chris -a upboundcare 
Adding robot "chris" to team "test123"
```
```
up robot team list chris -a upboundcare
TEAMS
test678
test123
```
```
up robot team leave test123 chris -a upboundcare
Are you sure you want to remove this robot from the team? This cannot be undone [y/n]: y
Removing robot "chris" from team "test123"
Removed robot "chris" from team "test123"
```

feat(robot): add robot team membership

---

pkg/migration/category/modifier.go

fixes the following issue:
```
up alpha migration import --unpause-after-import 
-i ../xp-state-20240709125414.tar.gz
Importing control plane state...
✓   Reading state from the archive... Done! 👀                                                                   
✓   Importing base resources... 52 resources imported! 📥                                                        
✓   Waiting for XRDs... Established! ⏳                                                                          
✓   Waiting for Packages... Installed and Healthy! ⏳                                                            
✓   Importing remaining resources... 38 resources imported! 📥                                                   
▀  Finalizing import...  (0s)up: error: migration.importCmd.Run(): cannot unpause …
```

fix(migration): fix unpause with dynamicClient gvr - cannot unpause composites: cannot list resources

---

pkg/migration/exporter/export.go

add option to skip crossplane resources during export
tested with: 
```
up alpha migration export --kubeconfig=kubeconfig --exclude-resources=configurations.pkg.crossplane.io,configurationrevisions.pkg.crossplane.io --yes
```
Fixes #
I have:

feat(skip): add an option to skip crossplane resources

---

cmd/up/query/get.go

This code path was not yet ported after the Spaces profiles were removed.
Instead of using the profile to call the Query API, parse the URL of the controlplane and go to the base path.

get: fix kubeconfig logic to call query API without profiles

---

cmd/up/query/run.go
go.mod
go.sum

Making use of https://github.com/upbound/spaces/pull/1434:
Needs https://github.com/upbound/spaces/pull/1456 for sorting.

get+query: add columns

---

internal/version/version.go

Fixes upbound/team-orchestration#217
I have:

bump connect-agent version

---

cmd/up/space/init.go

Set default before overriding with provided values.
I have:
Tested locally.

move defaults before overrides

---

cmd/up/controlplane/connector/install.go
cmd/up/controlplane/connector/uninstall.go
internal/version/version.go

- set mcp-connector registry to xpkg.upbound.io/spaces-artifacts
- set version to 0.7.0, use the same process like space connect agent
Fixes #590
I have:
```
NAME         	NAMESPACE     	REVISION	UPDATED                              	STATUS         	CHART                          	APP VERSION                      
mcp-connector	kube-system   	1       	2024-08-26 14:59:19.146175 +0200 CEST	deployed	mcp-connector-0.7.0            	0.7.0  
```

feat(oci): install mcp-connector from oci-registry

---

.github/workflows/ci.yml
cmd/up/space/connect.go

Use registry credentials and pull secret when installing the agent.
The former is to fetch the chart, the latter is for the pod images.
I have:
Connected a space locally.

require username/password for agent chart install

---

install.sh

Added support for Linux aarch64 installation of up.
Fixes #
- inability to install up on aarch64 linux.
I have:
- [ x] Read and followed Upbound's [contribution process](https://git.io/fj2m9).
Create a `Dockerfile` with the following content.
```
FROM ubuntu:latest
RUN apt-get update && apt-get install -y bash curl
RUN curl -sL \
"https://raw.githubusercontent.com/upbound/up/refs/heads/feature-aarch-support/install.sh" \
-o "install.sh" && \
sh ./install.sh && \
rm ./install.sh && \
mv ./up /usr/local/bin
ENTRYPOINT ["bash"]
```
```
docker build -t aarch64-up-cli .
```
```
docker run -it aarch64-up-cli:latest
```
Then `up` on the command line in the linux container.

add aarch64 support
